// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"goshop/internal/order/model"

	mock "github.com/stretchr/testify/mock"
)

// NewCouponRepository creates a new instance of CouponRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCouponRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CouponRepository {
	mock := &CouponRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CouponRepository is an autogenerated mock type for the CouponRepository type
type CouponRepository struct {
	mock.Mock
}

type CouponRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CouponRepository) EXPECT() *CouponRepository_Expecter {
	return &CouponRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type CouponRepository
func (_mock *CouponRepository) Create(ctx context.Context, coupon *model.Coupon) error {
	ret := _mock.Called(ctx, coupon)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Coupon) error); ok {
		r0 = returnFunc(ctx, coupon)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CouponRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CouponRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - coupon *model.Coupon
func (_e *CouponRepository_Expecter) Create(ctx interface{}, coupon interface{}) *CouponRepository_Create_Call {
	return &CouponRepository_Create_Call{Call: _e.mock.On("Create", ctx, coupon)}
}

func (_c *CouponRepository_Create_Call) Run(run func(ctx context.Context, coupon *model.Coupon)) *CouponRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Coupon
		if args[1] != nil {
			arg1 = args[1].(*model.Coupon)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CouponRepository_Create_Call) Return(err error) *CouponRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CouponRepository_Create_Call) RunAndReturn(run func(ctx context.Context, coupon *model.Coupon) error) *CouponRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCode provides a mock function for the type CouponRepository
func (_mock *CouponRepository) GetByCode(ctx context.Context, code string) (*model.Coupon, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 *model.Coupon
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Coupon, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Coupon); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Coupon)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CouponRepository_GetByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCode'
type CouponRepository_GetByCode_Call struct {
	*mock.Call
}

// GetByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *CouponRepository_Expecter) GetByCode(ctx interface{}, code interface{}) *CouponRepository_GetByCode_Call {
	return &CouponRepository_GetByCode_Call{Call: _e.mock.On("GetByCode", ctx, code)}
}

func (_c *CouponRepository_GetByCode_Call) Run(run func(ctx context.Context, code string)) *CouponRepository_GetByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CouponRepository_GetByCode_Call) Return(coupon *model.Coupon, err error) *CouponRepository_GetByCode_Call {
	_c.Call.Return(coupon, err)
	return _c
}

func (_c *CouponRepository_GetByCode_Call) RunAndReturn(run func(ctx context.Context, code string) (*model.Coupon, error)) *CouponRepository_GetByCode_Call {
	_c.Call.Return(run)
	return _c
}

// IncrUsedCount provides a mock function for the type CouponRepository
func (_mock *CouponRepository) IncrUsedCount(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrUsedCount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CouponRepository_IncrUsedCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrUsedCount'
type CouponRepository_IncrUsedCount_Call struct {
	*mock.Call
}

// IncrUsedCount is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *CouponRepository_Expecter) IncrUsedCount(ctx interface{}, id interface{}) *CouponRepository_IncrUsedCount_Call {
	return &CouponRepository_IncrUsedCount_Call{Call: _e.mock.On("IncrUsedCount", ctx, id)}
}

func (_c *CouponRepository_IncrUsedCount_Call) Run(run func(ctx context.Context, id string)) *CouponRepository_IncrUsedCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CouponRepository_IncrUsedCount_Call) Return(err error) *CouponRepository_IncrUsedCount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CouponRepository_IncrUsedCount_Call) RunAndReturn(run func(ctx context.Context, id string) error) *CouponRepository_IncrUsedCount_Call {
	_c.Call.Return(run)
	return _c
}
