// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"goshop/internal/order/domain"
	"goshop/internal/order/model"
	"goshop/pkg/paging"

	mock "github.com/stretchr/testify/mock"
)

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function for the type OrderRepository
func (_mock *OrderRepository) CreateOrder(ctx context.Context, userID string, lines []*model.OrderLine, couponCode string, discountAmount float64) (*model.Order, error) {
	ret := _mock.Called(ctx, userID, lines, couponCode, discountAmount)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []*model.OrderLine, string, float64) (*model.Order, error)); ok {
		return returnFunc(ctx, userID, lines, couponCode, discountAmount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []*model.OrderLine, string, float64) *model.Order); ok {
		r0 = returnFunc(ctx, userID, lines, couponCode, discountAmount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []*model.OrderLine, string, float64) error); ok {
		r1 = returnFunc(ctx, userID, lines, couponCode, discountAmount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderRepository_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderRepository_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - lines []*model.OrderLine
//   - couponCode string
//   - discountAmount float64
func (_e *OrderRepository_Expecter) CreateOrder(ctx interface{}, userID interface{}, lines interface{}, couponCode interface{}, discountAmount interface{}) *OrderRepository_CreateOrder_Call {
	return &OrderRepository_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, userID, lines, couponCode, discountAmount)}
}

func (_c *OrderRepository_CreateOrder_Call) Run(run func(ctx context.Context, userID string, lines []*model.OrderLine, couponCode string, discountAmount float64)) *OrderRepository_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*model.OrderLine
		if args[2] != nil {
			arg2 = args[2].([]*model.OrderLine)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 float64
		if args[4] != nil {
			arg4 = args[4].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *OrderRepository_CreateOrder_Call) Return(order *model.Order, err error) *OrderRepository_CreateOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderRepository_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, userID string, lines []*model.OrderLine, couponCode string, discountAmount float64) (*model.Order, error)) *OrderRepository_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetMyOrders provides a mock function for the type OrderRepository
func (_mock *OrderRepository) GetMyOrders(ctx context.Context, req *domain.ListOrderReq) ([]*model.Order, *paging.Pagination, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetMyOrders")
	}

	var r0 []*model.Order
	var r1 *paging.Pagination
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.ListOrderReq) ([]*model.Order, *paging.Pagination, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.ListOrderReq) []*model.Order); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.ListOrderReq) *paging.Pagination); ok {
		r1 = returnFunc(ctx, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*paging.Pagination)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *domain.ListOrderReq) error); ok {
		r2 = returnFunc(ctx, req)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// OrderRepository_GetMyOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMyOrders'
type OrderRepository_GetMyOrders_Call struct {
	*mock.Call
}

// GetMyOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - req *domain.ListOrderReq
func (_e *OrderRepository_Expecter) GetMyOrders(ctx interface{}, req interface{}) *OrderRepository_GetMyOrders_Call {
	return &OrderRepository_GetMyOrders_Call{Call: _e.mock.On("GetMyOrders", ctx, req)}
}

func (_c *OrderRepository_GetMyOrders_Call) Run(run func(ctx context.Context, req *domain.ListOrderReq)) *OrderRepository_GetMyOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.ListOrderReq
		if args[1] != nil {
			arg1 = args[1].(*domain.ListOrderReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepository_GetMyOrders_Call) Return(orders []*model.Order, pagination *paging.Pagination, err error) *OrderRepository_GetMyOrders_Call {
	_c.Call.Return(orders, pagination, err)
	return _c
}

func (_c *OrderRepository_GetMyOrders_Call) RunAndReturn(run func(ctx context.Context, req *domain.ListOrderReq) ([]*model.Order, *paging.Pagination, error)) *OrderRepository_GetMyOrders_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderByID provides a mock function for the type OrderRepository
func (_mock *OrderRepository) GetOrderByID(ctx context.Context, id string, preload bool) (*model.Order, error) {
	ret := _mock.Called(ctx, id, preload)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByID")
	}

	var r0 *model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) (*model.Order, error)); ok {
		return returnFunc(ctx, id, preload)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) *model.Order); ok {
		r0 = returnFunc(ctx, id, preload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = returnFunc(ctx, id, preload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderRepository_GetOrderByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByID'
type OrderRepository_GetOrderByID_Call struct {
	*mock.Call
}

// GetOrderByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - preload bool
func (_e *OrderRepository_Expecter) GetOrderByID(ctx interface{}, id interface{}, preload interface{}) *OrderRepository_GetOrderByID_Call {
	return &OrderRepository_GetOrderByID_Call{Call: _e.mock.On("GetOrderByID", ctx, id, preload)}
}

func (_c *OrderRepository_GetOrderByID_Call) Run(run func(ctx context.Context, id string, preload bool)) *OrderRepository_GetOrderByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OrderRepository_GetOrderByID_Call) Return(order *model.Order, err error) *OrderRepository_GetOrderByID_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderRepository_GetOrderByID_Call) RunAndReturn(run func(ctx context.Context, id string, preload bool) (*model.Order, error)) *OrderRepository_GetOrderByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrder provides a mock function for the type OrderRepository
func (_mock *OrderRepository) UpdateOrder(ctx context.Context, order *model.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderRepository_UpdateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrder'
type OrderRepository_UpdateOrder_Call struct {
	*mock.Call
}

// UpdateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order *model.Order
func (_e *OrderRepository_Expecter) UpdateOrder(ctx interface{}, order interface{}) *OrderRepository_UpdateOrder_Call {
	return &OrderRepository_UpdateOrder_Call{Call: _e.mock.On("UpdateOrder", ctx, order)}
}

func (_c *OrderRepository_UpdateOrder_Call) Run(run func(ctx context.Context, order *model.Order)) *OrderRepository_UpdateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Order
		if args[1] != nil {
			arg1 = args[1].(*model.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepository_UpdateOrder_Call) Return(err error) *OrderRepository_UpdateOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderRepository_UpdateOrder_Call) RunAndReturn(run func(ctx context.Context, order *model.Order) error) *OrderRepository_UpdateOrder_Call {
	_c.Call.Return(run)
	return _c
}
