// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"goshop/pkg/dbs"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewDatabase creates a new instance of Database. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *Database {
	mock := &Database{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Database is an autogenerated mock type for the Database type
type Database struct {
	mock.Mock
}

type Database_Expecter struct {
	mock *mock.Mock
}

func (_m *Database) EXPECT() *Database_Expecter {
	return &Database_Expecter{mock: &_m.Mock}
}

// AutoMigrate provides a mock function for the type Database
func (_mock *Database) AutoMigrate(models ...any) error {
	var tmpRet mock.Arguments
	if len(models) > 0 {
		tmpRet = _mock.Called(models)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AutoMigrate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(...any) error); ok {
		r0 = returnFunc(models...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_AutoMigrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutoMigrate'
type Database_AutoMigrate_Call struct {
	*mock.Call
}

// AutoMigrate is a helper method to define mock.On call
//   - models ...any
func (_e *Database_Expecter) AutoMigrate(models ...interface{}) *Database_AutoMigrate_Call {
	return &Database_AutoMigrate_Call{Call: _e.mock.On("AutoMigrate",
		append([]interface{}{}, models...)...)}
}

func (_c *Database_AutoMigrate_Call) Run(run func(models ...any)) *Database_AutoMigrate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []any
		var variadicArgs []any
		if len(args) > 0 {
			variadicArgs = args[0].([]any)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *Database_AutoMigrate_Call) Return(err error) *Database_AutoMigrate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_AutoMigrate_Call) RunAndReturn(run func(models ...any) error) *Database_AutoMigrate_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type Database
func (_mock *Database) Count(ctx context.Context, model any, total *int64, opts ...dbs.FindOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, model, total, opts)
	} else {
		tmpRet = _mock.Called(ctx, model, total)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, *int64, ...dbs.FindOption) error); ok {
		r0 = returnFunc(ctx, model, total, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type Database_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - model any
//   - total *int64
//   - opts ...dbs.FindOption
func (_e *Database_Expecter) Count(ctx interface{}, model interface{}, total interface{}, opts ...interface{}) *Database_Count_Call {
	return &Database_Count_Call{Call: _e.mock.On("Count",
		append([]interface{}{ctx, model, total}, opts...)...)}
}

func (_c *Database_Count_Call) Run(run func(ctx context.Context, model any, total *int64, opts ...dbs.FindOption)) *Database_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 *int64
		if args[2] != nil {
			arg2 = args[2].(*int64)
		}
		var arg3 []dbs.FindOption
		var variadicArgs []dbs.FindOption
		if len(args) > 3 {
			variadicArgs = args[3].([]dbs.FindOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Database_Count_Call) Return(err error) *Database_Count_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_Count_Call) RunAndReturn(run func(ctx context.Context, model any, total *int64, opts ...dbs.FindOption) error) *Database_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type Database
func (_mock *Database) Create(ctx context.Context, doc any) error {
	ret := _mock.Called(ctx, doc)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any) error); ok {
		r0 = returnFunc(ctx, doc)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Database_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - doc any
func (_e *Database_Expecter) Create(ctx interface{}, doc interface{}) *Database_Create_Call {
	return &Database_Create_Call{Call: _e.mock.On("Create", ctx, doc)}
}

func (_c *Database_Create_Call) Run(run func(ctx context.Context, doc any)) *Database_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_Create_Call) Return(err error) *Database_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_Create_Call) RunAndReturn(run func(ctx context.Context, doc any) error) *Database_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInBatches provides a mock function for the type Database
func (_mock *Database) CreateInBatches(ctx context.Context, docs any, batchSize int) error {
	ret := _mock.Called(ctx, docs, batchSize)

	if len(ret) == 0 {
		panic("no return value specified for CreateInBatches")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, int) error); ok {
		r0 = returnFunc(ctx, docs, batchSize)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_CreateInBatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInBatches'
type Database_CreateInBatches_Call struct {
	*mock.Call
}

// CreateInBatches is a helper method to define mock.On call
//   - ctx context.Context
//   - docs any
//   - batchSize int
func (_e *Database_Expecter) CreateInBatches(ctx interface{}, docs interface{}, batchSize interface{}) *Database_CreateInBatches_Call {
	return &Database_CreateInBatches_Call{Call: _e.mock.On("CreateInBatches", ctx, docs, batchSize)}
}

func (_c *Database_CreateInBatches_Call) Run(run func(ctx context.Context, docs any, batchSize int)) *Database_CreateInBatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Database_CreateInBatches_Call) Return(err error) *Database_CreateInBatches_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_CreateInBatches_Call) RunAndReturn(run func(ctx context.Context, docs any, batchSize int) error) *Database_CreateInBatches_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type Database
func (_mock *Database) Delete(ctx context.Context, value any, opts ...dbs.FindOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, value, opts)
	} else {
		tmpRet = _mock.Called(ctx, value)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, ...dbs.FindOption) error); ok {
		r0 = returnFunc(ctx, value, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Database_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - value any
//   - opts ...dbs.FindOption
func (_e *Database_Expecter) Delete(ctx interface{}, value interface{}, opts ...interface{}) *Database_Delete_Call {
	return &Database_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{ctx, value}, opts...)...)}
}

func (_c *Database_Delete_Call) Run(run func(ctx context.Context, value any, opts ...dbs.FindOption)) *Database_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 []dbs.FindOption
		var variadicArgs []dbs.FindOption
		if len(args) > 2 {
			variadicArgs = args[2].([]dbs.FindOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Database_Delete_Call) Return(err error) *Database_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_Delete_Call) RunAndReturn(run func(ctx context.Context, value any, opts ...dbs.FindOption) error) *Database_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type Database
func (_mock *Database) Find(ctx context.Context, result any, opts ...dbs.FindOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, result, opts)
	} else {
		tmpRet = _mock.Called(ctx, result)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, ...dbs.FindOption) error); ok {
		r0 = returnFunc(ctx, result, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type Database_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - result any
//   - opts ...dbs.FindOption
func (_e *Database_Expecter) Find(ctx interface{}, result interface{}, opts ...interface{}) *Database_Find_Call {
	return &Database_Find_Call{Call: _e.mock.On("Find",
		append([]interface{}{ctx, result}, opts...)...)}
}

func (_c *Database_Find_Call) Run(run func(ctx context.Context, result any, opts ...dbs.FindOption)) *Database_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 []dbs.FindOption
		var variadicArgs []dbs.FindOption
		if len(args) > 2 {
			variadicArgs = args[2].([]dbs.FindOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Database_Find_Call) Return(err error) *Database_Find_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_Find_Call) RunAndReturn(run func(ctx context.Context, result any, opts ...dbs.FindOption) error) *Database_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type Database
func (_mock *Database) FindById(ctx context.Context, id string, result any) error {
	ret := _mock.Called(ctx, id, result)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, id, result)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type Database_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - result any
func (_e *Database_Expecter) FindById(ctx interface{}, id interface{}, result interface{}) *Database_FindById_Call {
	return &Database_FindById_Call{Call: _e.mock.On("FindById", ctx, id, result)}
}

func (_c *Database_FindById_Call) Run(run func(ctx context.Context, id string, result any)) *Database_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Database_FindById_Call) Return(err error) *Database_FindById_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_FindById_Call) RunAndReturn(run func(ctx context.Context, id string, result any) error) *Database_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// FindOne provides a mock function for the type Database
func (_mock *Database) FindOne(ctx context.Context, result any, opts ...dbs.FindOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, result, opts)
	} else {
		tmpRet = _mock.Called(ctx, result)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindOne")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any, ...dbs.FindOption) error); ok {
		r0 = returnFunc(ctx, result, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_FindOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOne'
type Database_FindOne_Call struct {
	*mock.Call
}

// FindOne is a helper method to define mock.On call
//   - ctx context.Context
//   - result any
//   - opts ...dbs.FindOption
func (_e *Database_Expecter) FindOne(ctx interface{}, result interface{}, opts ...interface{}) *Database_FindOne_Call {
	return &Database_FindOne_Call{Call: _e.mock.On("FindOne",
		append([]interface{}{ctx, result}, opts...)...)}
}

func (_c *Database_FindOne_Call) Run(run func(ctx context.Context, result any, opts ...dbs.FindOption)) *Database_FindOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 []dbs.FindOption
		var variadicArgs []dbs.FindOption
		if len(args) > 2 {
			variadicArgs = args[2].([]dbs.FindOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Database_FindOne_Call) Return(err error) *Database_FindOne_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_FindOne_Call) RunAndReturn(run func(ctx context.Context, result any, opts ...dbs.FindOption) error) *Database_FindOne_Call {
	_c.Call.Return(run)
	return _c
}

// GetDB provides a mock function for the type Database
func (_mock *Database) GetDB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// Database_GetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDB'
type Database_GetDB_Call struct {
	*mock.Call
}

// GetDB is a helper method to define mock.On call
func (_e *Database_Expecter) GetDB() *Database_GetDB_Call {
	return &Database_GetDB_Call{Call: _e.mock.On("GetDB")}
}

func (_c *Database_GetDB_Call) Run(run func()) *Database_GetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Database_GetDB_Call) Return(dB *gorm.DB) *Database_GetDB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *Database_GetDB_Call) RunAndReturn(run func() *gorm.DB) *Database_GetDB_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type Database
func (_mock *Database) Update(ctx context.Context, doc any) error {
	ret := _mock.Called(ctx, doc)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any) error); ok {
		r0 = returnFunc(ctx, doc)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Database_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - doc any
func (_e *Database_Expecter) Update(ctx interface{}, doc interface{}) *Database_Update_Call {
	return &Database_Update_Call{Call: _e.mock.On("Update", ctx, doc)}
}

func (_c *Database_Update_Call) Run(run func(ctx context.Context, doc any)) *Database_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_Update_Call) Return(err error) *Database_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_Update_Call) RunAndReturn(run func(ctx context.Context, doc any) error) *Database_Update_Call {
	_c.Call.Return(run)
	return _c
}

// WithTransaction provides a mock function for the type Database
func (_mock *Database) WithTransaction(function func() error) error {
	ret := _mock.Called(function)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(func() error) error); ok {
		r0 = returnFunc(function)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type Database_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - function func() error
func (_e *Database_Expecter) WithTransaction(function interface{}) *Database_WithTransaction_Call {
	return &Database_WithTransaction_Call{Call: _e.mock.On("WithTransaction", function)}
}

func (_c *Database_WithTransaction_Call) Run(run func(function func() error)) *Database_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func() error
		if args[0] != nil {
			arg0 = args[0].(func() error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Database_WithTransaction_Call) Return(err error) *Database_WithTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_WithTransaction_Call) RunAndReturn(run func(function func() error) error) *Database_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}
