// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"goshop/pkg/dbs"

	mock "github.com/stretchr/testify/mock"
)

// NewFindOption creates a new instance of FindOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFindOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *FindOption {
	mock := &FindOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FindOption is an autogenerated mock type for the FindOption type
type FindOption struct {
	mock.Mock
}

type FindOption_Expecter struct {
	mock *mock.Mock
}

func (_m *FindOption) EXPECT() *FindOption_Expecter {
	return &FindOption_Expecter{mock: &_m.Mock}
}

// apply provides a mock function for the type FindOption
func (_mock *FindOption) apply(optionMoqParam *dbs.option) {
	_mock.Called(optionMoqParam)
	return
}

// FindOption_apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'apply'
type FindOption_apply_Call struct {
	*mock.Call
}

// apply is a helper method to define mock.On call
//   - optionMoqParam *dbs.option
func (_e *FindOption_Expecter) apply(optionMoqParam interface{}) *FindOption_apply_Call {
	return &FindOption_apply_Call{Call: _e.mock.On("apply", optionMoqParam)}
}

func (_c *FindOption_apply_Call) Run(run func(optionMoqParam *dbs.option)) *FindOption_apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *dbs.option
		if args[0] != nil {
			arg0 = args[0].(*dbs.option)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FindOption_apply_Call) Return() *FindOption_apply_Call {
	_c.Call.Return()
	return _c
}

func (_c *FindOption_apply_Call) RunAndReturn(run func(optionMoqParam *dbs.option)) *FindOption_apply_Call {
	_c.Run(run)
	return _c
}
