// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"goshop/internal/cart/domain"
	"goshop/internal/cart/model"

	mock "github.com/stretchr/testify/mock"
)

// NewCartService creates a new instance of CartService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCartService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CartService {
	mock := &CartService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CartService is an autogenerated mock type for the CartService type
type CartService struct {
	mock.Mock
}

type CartService_Expecter struct {
	mock *mock.Mock
}

func (_m *CartService) EXPECT() *CartService_Expecter {
	return &CartService_Expecter{mock: &_m.Mock}
}

// AddProduct provides a mock function for the type CartService
func (_mock *CartService) AddProduct(ctx context.Context, req *domain.AddProductReq) (*model.Cart, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AddProduct")
	}

	var r0 *model.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AddProductReq) (*model.Cart, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AddProductReq) *model.Cart); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Cart)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.AddProductReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CartService_AddProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddProduct'
type CartService_AddProduct_Call struct {
	*mock.Call
}

// AddProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - req *domain.AddProductReq
func (_e *CartService_Expecter) AddProduct(ctx interface{}, req interface{}) *CartService_AddProduct_Call {
	return &CartService_AddProduct_Call{Call: _e.mock.On("AddProduct", ctx, req)}
}

func (_c *CartService_AddProduct_Call) Run(run func(ctx context.Context, req *domain.AddProductReq)) *CartService_AddProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AddProductReq
		if args[1] != nil {
			arg1 = args[1].(*domain.AddProductReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CartService_AddProduct_Call) Return(cart *model.Cart, err error) *CartService_AddProduct_Call {
	_c.Call.Return(cart, err)
	return _c
}

func (_c *CartService_AddProduct_Call) RunAndReturn(run func(ctx context.Context, req *domain.AddProductReq) (*model.Cart, error)) *CartService_AddProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetCartByUserID provides a mock function for the type CartService
func (_mock *CartService) GetCartByUserID(ctx context.Context, userID string) (*model.Cart, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCartByUserID")
	}

	var r0 *model.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Cart, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Cart); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Cart)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CartService_GetCartByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCartByUserID'
type CartService_GetCartByUserID_Call struct {
	*mock.Call
}

// GetCartByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *CartService_Expecter) GetCartByUserID(ctx interface{}, userID interface{}) *CartService_GetCartByUserID_Call {
	return &CartService_GetCartByUserID_Call{Call: _e.mock.On("GetCartByUserID", ctx, userID)}
}

func (_c *CartService_GetCartByUserID_Call) Run(run func(ctx context.Context, userID string)) *CartService_GetCartByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CartService_GetCartByUserID_Call) Return(cart *model.Cart, err error) *CartService_GetCartByUserID_Call {
	_c.Call.Return(cart, err)
	return _c
}

func (_c *CartService_GetCartByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) (*model.Cart, error)) *CartService_GetCartByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveProduct provides a mock function for the type CartService
func (_mock *CartService) RemoveProduct(ctx context.Context, req *domain.RemoveProductReq) (*model.Cart, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RemoveProduct")
	}

	var r0 *model.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.RemoveProductReq) (*model.Cart, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.RemoveProductReq) *model.Cart); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Cart)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.RemoveProductReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CartService_RemoveProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveProduct'
type CartService_RemoveProduct_Call struct {
	*mock.Call
}

// RemoveProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - req *domain.RemoveProductReq
func (_e *CartService_Expecter) RemoveProduct(ctx interface{}, req interface{}) *CartService_RemoveProduct_Call {
	return &CartService_RemoveProduct_Call{Call: _e.mock.On("RemoveProduct", ctx, req)}
}

func (_c *CartService_RemoveProduct_Call) Run(run func(ctx context.Context, req *domain.RemoveProductReq)) *CartService_RemoveProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.RemoveProductReq
		if args[1] != nil {
			arg1 = args[1].(*domain.RemoveProductReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CartService_RemoveProduct_Call) Return(cart *model.Cart, err error) *CartService_RemoveProduct_Call {
	_c.Call.Return(cart, err)
	return _c
}

func (_c *CartService_RemoveProduct_Call) RunAndReturn(run func(ctx context.Context, req *domain.RemoveProductReq) (*model.Cart, error)) *CartService_RemoveProduct_Call {
	_c.Call.Return(run)
	return _c
}
