all: false
dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceName | snakecase}}.go"
force-file-write: true
formatter: goimports
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}'
recursive: false
require-template-schema-exists: true
template: testify
template-schema: '{{.Template}}.schema.json'
packages:
  goshop:
    config:
      all: true
