// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"goshop/internal/order/domain"
	"goshop/internal/order/model"

	mock "github.com/stretchr/testify/mock"
)

// NewCouponService creates a new instance of CouponService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCouponService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CouponService {
	mock := &CouponService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CouponService is an autogenerated mock type for the CouponService type
type CouponService struct {
	mock.Mock
}

type CouponService_Expecter struct {
	mock *mock.Mock
}

func (_m *CouponService) EXPECT() *CouponService_Expecter {
	return &CouponService_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type CouponService
func (_mock *CouponService) Apply(ctx context.Context, code string, totalPrice float64) (float64, *model.Coupon, error) {
	ret := _mock.Called(ctx, code, totalPrice)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 float64
	var r1 *model.Coupon
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, float64) (float64, *model.Coupon, error)); ok {
		return returnFunc(ctx, code, totalPrice)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, float64) float64); ok {
		r0 = returnFunc(ctx, code, totalPrice)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, float64) *model.Coupon); ok {
		r1 = returnFunc(ctx, code, totalPrice)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.Coupon)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, float64) error); ok {
		r2 = returnFunc(ctx, code, totalPrice)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// CouponService_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type CouponService_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - totalPrice float64
func (_e *CouponService_Expecter) Apply(ctx interface{}, code interface{}, totalPrice interface{}) *CouponService_Apply_Call {
	return &CouponService_Apply_Call{Call: _e.mock.On("Apply", ctx, code, totalPrice)}
}

func (_c *CouponService_Apply_Call) Run(run func(ctx context.Context, code string, totalPrice float64)) *CouponService_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CouponService_Apply_Call) Return(discountAmount float64, coupon *model.Coupon, err error) *CouponService_Apply_Call {
	_c.Call.Return(discountAmount, coupon, err)
	return _c
}

func (_c *CouponService_Apply_Call) RunAndReturn(run func(ctx context.Context, code string, totalPrice float64) (float64, *model.Coupon, error)) *CouponService_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type CouponService
func (_mock *CouponService) Create(ctx context.Context, req *domain.CreateCouponReq) (*model.Coupon, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Coupon
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.CreateCouponReq) (*model.Coupon, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.CreateCouponReq) *model.Coupon); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Coupon)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.CreateCouponReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CouponService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CouponService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req *domain.CreateCouponReq
func (_e *CouponService_Expecter) Create(ctx interface{}, req interface{}) *CouponService_Create_Call {
	return &CouponService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *CouponService_Create_Call) Run(run func(ctx context.Context, req *domain.CreateCouponReq)) *CouponService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.CreateCouponReq
		if args[1] != nil {
			arg1 = args[1].(*domain.CreateCouponReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CouponService_Create_Call) Return(coupon *model.Coupon, err error) *CouponService_Create_Call {
	_c.Call.Return(coupon, err)
	return _c
}

func (_c *CouponService_Create_Call) RunAndReturn(run func(ctx context.Context, req *domain.CreateCouponReq) (*model.Coupon, error)) *CouponService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCode provides a mock function for the type CouponService
func (_mock *CouponService) GetByCode(ctx context.Context, code string) (*model.Coupon, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 *model.Coupon
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Coupon, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Coupon); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Coupon)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CouponService_GetByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCode'
type CouponService_GetByCode_Call struct {
	*mock.Call
}

// GetByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *CouponService_Expecter) GetByCode(ctx interface{}, code interface{}) *CouponService_GetByCode_Call {
	return &CouponService_GetByCode_Call{Call: _e.mock.On("GetByCode", ctx, code)}
}

func (_c *CouponService_GetByCode_Call) Run(run func(ctx context.Context, code string)) *CouponService_GetByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CouponService_GetByCode_Call) Return(coupon *model.Coupon, err error) *CouponService_GetByCode_Call {
	_c.Call.Return(coupon, err)
	return _c
}

func (_c *CouponService_GetByCode_Call) RunAndReturn(run func(ctx context.Context, code string) (*model.Coupon, error)) *CouponService_GetByCode_Call {
	_c.Call.Return(run)
	return _c
}

// IncrUsedCount provides a mock function for the type CouponService
func (_mock *CouponService) IncrUsedCount(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrUsedCount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CouponService_IncrUsedCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrUsedCount'
type CouponService_IncrUsedCount_Call struct {
	*mock.Call
}

// IncrUsedCount is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *CouponService_Expecter) IncrUsedCount(ctx interface{}, id interface{}) *CouponService_IncrUsedCount_Call {
	return &CouponService_IncrUsedCount_Call{Call: _e.mock.On("IncrUsedCount", ctx, id)}
}

func (_c *CouponService_IncrUsedCount_Call) Run(run func(ctx context.Context, id string)) *CouponService_IncrUsedCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CouponService_IncrUsedCount_Call) Return(err error) *CouponService_IncrUsedCount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CouponService_IncrUsedCount_Call) RunAndReturn(run func(ctx context.Context, id string) error) *CouponService_IncrUsedCount_Call {
	_c.Call.Return(run)
	return _c
}
