// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"goshop/internal/order/dto"
	"goshop/internal/order/model"
	"goshop/pkg/paging"

	mock "github.com/stretchr/testify/mock"
)

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function for the type OrderService
func (_mock *OrderService) CancelOrder(ctx context.Context, orderID string, userID string) (*model.Order, error) {
	ret := _mock.Called(ctx, orderID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 *model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.Order, error)); ok {
		return returnFunc(ctx, orderID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.Order); ok {
		r0 = returnFunc(ctx, orderID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, orderID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type OrderService_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - userID string
func (_e *OrderService_Expecter) CancelOrder(ctx interface{}, orderID interface{}, userID interface{}) *OrderService_CancelOrder_Call {
	return &OrderService_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, orderID, userID)}
}

func (_c *OrderService_CancelOrder_Call) Run(run func(ctx context.Context, orderID string, userID string)) *OrderService_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OrderService_CancelOrder_Call) Return(order *model.Order, err error) *OrderService_CancelOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderService_CancelOrder_Call) RunAndReturn(run func(ctx context.Context, orderID string, userID string) (*model.Order, error)) *OrderService_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetMyOrders provides a mock function for the type OrderService
func (_mock *OrderService) GetMyOrders(ctx context.Context, req *dto.ListOrderReq) ([]*model.Order, *paging.Pagination, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetMyOrders")
	}

	var r0 []*model.Order
	var r1 *paging.Pagination
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.ListOrderReq) ([]*model.Order, *paging.Pagination, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.ListOrderReq) []*model.Order); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.ListOrderReq) *paging.Pagination); ok {
		r1 = returnFunc(ctx, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*paging.Pagination)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *dto.ListOrderReq) error); ok {
		r2 = returnFunc(ctx, req)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// OrderService_GetMyOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMyOrders'
type OrderService_GetMyOrders_Call struct {
	*mock.Call
}

// GetMyOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.ListOrderReq
func (_e *OrderService_Expecter) GetMyOrders(ctx interface{}, req interface{}) *OrderService_GetMyOrders_Call {
	return &OrderService_GetMyOrders_Call{Call: _e.mock.On("GetMyOrders", ctx, req)}
}

func (_c *OrderService_GetMyOrders_Call) Run(run func(ctx context.Context, req *dto.ListOrderReq)) *OrderService_GetMyOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.ListOrderReq
		if args[1] != nil {
			arg1 = args[1].(*dto.ListOrderReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderService_GetMyOrders_Call) Return(orders []*model.Order, pagination *paging.Pagination, err error) *OrderService_GetMyOrders_Call {
	_c.Call.Return(orders, pagination, err)
	return _c
}

func (_c *OrderService_GetMyOrders_Call) RunAndReturn(run func(ctx context.Context, req *dto.ListOrderReq) ([]*model.Order, *paging.Pagination, error)) *OrderService_GetMyOrders_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderByID provides a mock function for the type OrderService
func (_mock *OrderService) GetOrderByID(ctx context.Context, id string) (*model.Order, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByID")
	}

	var r0 *model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Order, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Order); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_GetOrderByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByID'
type OrderService_GetOrderByID_Call struct {
	*mock.Call
}

// GetOrderByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *OrderService_Expecter) GetOrderByID(ctx interface{}, id interface{}) *OrderService_GetOrderByID_Call {
	return &OrderService_GetOrderByID_Call{Call: _e.mock.On("GetOrderByID", ctx, id)}
}

func (_c *OrderService_GetOrderByID_Call) Run(run func(ctx context.Context, id string)) *OrderService_GetOrderByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderService_GetOrderByID_Call) Return(order *model.Order, err error) *OrderService_GetOrderByID_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderService_GetOrderByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Order, error)) *OrderService_GetOrderByID_Call {
	_c.Call.Return(run)
	return _c
}

// PlaceOrder provides a mock function for the type OrderService
func (_mock *OrderService) PlaceOrder(ctx context.Context, req *dto.PlaceOrderReq) (*model.Order, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PlaceOrder")
	}

	var r0 *model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.PlaceOrderReq) (*model.Order, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.PlaceOrderReq) *model.Order); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.PlaceOrderReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_PlaceOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlaceOrder'
type OrderService_PlaceOrder_Call struct {
	*mock.Call
}

// PlaceOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.PlaceOrderReq
func (_e *OrderService_Expecter) PlaceOrder(ctx interface{}, req interface{}) *OrderService_PlaceOrder_Call {
	return &OrderService_PlaceOrder_Call{Call: _e.mock.On("PlaceOrder", ctx, req)}
}

func (_c *OrderService_PlaceOrder_Call) Run(run func(ctx context.Context, req *dto.PlaceOrderReq)) *OrderService_PlaceOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.PlaceOrderReq
		if args[1] != nil {
			arg1 = args[1].(*dto.PlaceOrderReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderService_PlaceOrder_Call) Return(order *model.Order, err error) *OrderService_PlaceOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderService_PlaceOrder_Call) RunAndReturn(run func(ctx context.Context, req *dto.PlaceOrderReq) (*model.Order, error)) *OrderService_PlaceOrder_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderStatus provides a mock function for the type OrderService
func (_mock *OrderService) UpdateOrderStatus(ctx context.Context, orderID string, status model.OrderStatus) (*model.Order, error) {
	ret := _mock.Called(ctx, orderID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatus")
	}

	var r0 *model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.OrderStatus) (*model.Order, error)); ok {
		return returnFunc(ctx, orderID, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.OrderStatus) *model.Order); ok {
		r0 = returnFunc(ctx, orderID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, model.OrderStatus) error); ok {
		r1 = returnFunc(ctx, orderID, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_UpdateOrderStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderStatus'
type OrderService_UpdateOrderStatus_Call struct {
	*mock.Call
}

// UpdateOrderStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - status model.OrderStatus
func (_e *OrderService_Expecter) UpdateOrderStatus(ctx interface{}, orderID interface{}, status interface{}) *OrderService_UpdateOrderStatus_Call {
	return &OrderService_UpdateOrderStatus_Call{Call: _e.mock.On("UpdateOrderStatus", ctx, orderID, status)}
}

func (_c *OrderService_UpdateOrderStatus_Call) Run(run func(ctx context.Context, orderID string, status model.OrderStatus)) *OrderService_UpdateOrderStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.OrderStatus
		if args[2] != nil {
			arg2 = args[2].(model.OrderStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OrderService_UpdateOrderStatus_Call) Return(order *model.Order, err error) *OrderService_UpdateOrderStatus_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderService_UpdateOrderStatus_Call) RunAndReturn(run func(ctx context.Context, orderID string, status model.OrderStatus) (*model.Order, error)) *OrderService_UpdateOrderStatus_Call {
	_c.Call.Return(run)
	return _c
}
