apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ./docker-compose.yaml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: goshop
  name: goshop
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: goshop
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file ./docker-compose.yaml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/goshop-default: "true"
        io.kompose.service: goshop
    spec:
      containers:
        - env:
            - name: auth_secret
              value: auth_secret
            - name: database_uri
              value: postgres://goshop:goshopsecret@postgres:5432/goshop
            - name: port
              value: "8888"
            - name: redis_db
              value: "0"
            - name: redis_uri
              value: redis:6379
          image: goshop
          name: goshop
          ports:
            - containerPort: 8888
              hostPort: 8888
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
