// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewRedis creates a new instance of Redis. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedis(t interface {
	mock.TestingT
	Cleanup(func())
}) *Redis {
	mock := &Redis{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Redis is an autogenerated mock type for the Redis type
type Redis struct {
	mock.Mock
}

type Redis_Expecter struct {
	mock *mock.Mock
}

func (_m *Redis) EXPECT() *Redis_Expecter {
	return &Redis_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type Redis
func (_mock *Redis) Get(key string, value interface{}) error {
	ret := _mock.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = returnFunc(key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Redis_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Redis_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
//   - value interface{}
func (_e *Redis_Expecter) Get(key interface{}, value interface{}) *Redis_Get_Call {
	return &Redis_Get_Call{Call: _e.mock.On("Get", key, value)}
}

func (_c *Redis_Get_Call) Run(run func(key string, value interface{})) *Redis_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Redis_Get_Call) Return(err error) *Redis_Get_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Redis_Get_Call) RunAndReturn(run func(key string, value interface{}) error) *Redis_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Incr provides a mock function for the type Redis
func (_mock *Redis) Incr(key string, expiration time.Duration) (int64, error) {
	ret := _mock.Called(key, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Incr")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, time.Duration) (int64, error)); ok {
		return returnFunc(key, expiration)
	}
	if returnFunc, ok := ret.Get(0).(func(string, time.Duration) int64); ok {
		r0 = returnFunc(key, expiration)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(string, time.Duration) error); ok {
		r1 = returnFunc(key, expiration)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Redis_Incr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Incr'
type Redis_Incr_Call struct {
	*mock.Call
}

// Incr is a helper method to define mock.On call
//   - key string
//   - expiration time.Duration
func (_e *Redis_Expecter) Incr(key interface{}, expiration interface{}) *Redis_Incr_Call {
	return &Redis_Incr_Call{Call: _e.mock.On("Incr", key, expiration)}
}

func (_c *Redis_Incr_Call) Run(run func(key string, expiration time.Duration)) *Redis_Incr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Redis_Incr_Call) Return(n int64, err error) *Redis_Incr_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *Redis_Incr_Call) RunAndReturn(run func(key string, expiration time.Duration) (int64, error)) *Redis_Incr_Call {
	_c.Call.Return(run)
	return _c
}

// IsConnected provides a mock function for the type Redis
func (_mock *Redis) IsConnected() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsConnected")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Redis_IsConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConnected'
type Redis_IsConnected_Call struct {
	*mock.Call
}

// IsConnected is a helper method to define mock.On call
func (_e *Redis_Expecter) IsConnected() *Redis_IsConnected_Call {
	return &Redis_IsConnected_Call{Call: _e.mock.On("IsConnected")}
}

func (_c *Redis_IsConnected_Call) Run(run func()) *Redis_IsConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Redis_IsConnected_Call) Return(b bool) *Redis_IsConnected_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Redis_IsConnected_Call) RunAndReturn(run func() bool) *Redis_IsConnected_Call {
	_c.Call.Return(run)
	return _c
}

// Keys provides a mock function for the type Redis
func (_mock *Redis) Keys(pattern string) ([]string, error) {
	ret := _mock.Called(pattern)

	if len(ret) == 0 {
		panic("no return value specified for Keys")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return returnFunc(pattern)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(pattern)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(pattern)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Redis_Keys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Keys'
type Redis_Keys_Call struct {
	*mock.Call
}

// Keys is a helper method to define mock.On call
//   - pattern string
func (_e *Redis_Expecter) Keys(pattern interface{}) *Redis_Keys_Call {
	return &Redis_Keys_Call{Call: _e.mock.On("Keys", pattern)}
}

func (_c *Redis_Keys_Call) Run(run func(pattern string)) *Redis_Keys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Redis_Keys_Call) Return(strings []string, err error) *Redis_Keys_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *Redis_Keys_Call) RunAndReturn(run func(pattern string) ([]string, error)) *Redis_Keys_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type Redis
func (_mock *Redis) Remove(keys ...string) error {
	var tmpRet mock.Arguments
	if len(keys) > 0 {
		tmpRet = _mock.Called(keys)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(...string) error); ok {
		r0 = returnFunc(keys...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Redis_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type Redis_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - keys ...string
func (_e *Redis_Expecter) Remove(keys ...interface{}) *Redis_Remove_Call {
	return &Redis_Remove_Call{Call: _e.mock.On("Remove",
		append([]interface{}{}, keys...)...)}
}

func (_c *Redis_Remove_Call) Run(run func(keys ...string)) *Redis_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		var variadicArgs []string
		if len(args) > 0 {
			variadicArgs = args[0].([]string)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *Redis_Remove_Call) Return(err error) *Redis_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Redis_Remove_Call) RunAndReturn(run func(keys ...string) error) *Redis_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePattern provides a mock function for the type Redis
func (_mock *Redis) RemovePattern(pattern string) error {
	ret := _mock.Called(pattern)

	if len(ret) == 0 {
		panic("no return value specified for RemovePattern")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(pattern)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Redis_RemovePattern_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePattern'
type Redis_RemovePattern_Call struct {
	*mock.Call
}

// RemovePattern is a helper method to define mock.On call
//   - pattern string
func (_e *Redis_Expecter) RemovePattern(pattern interface{}) *Redis_RemovePattern_Call {
	return &Redis_RemovePattern_Call{Call: _e.mock.On("RemovePattern", pattern)}
}

func (_c *Redis_RemovePattern_Call) Run(run func(pattern string)) *Redis_RemovePattern_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Redis_RemovePattern_Call) Return(err error) *Redis_RemovePattern_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Redis_RemovePattern_Call) RunAndReturn(run func(pattern string) error) *Redis_RemovePattern_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type Redis
func (_mock *Redis) Set(key string, value interface{}) error {
	ret := _mock.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = returnFunc(key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Redis_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type Redis_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - value interface{}
func (_e *Redis_Expecter) Set(key interface{}, value interface{}) *Redis_Set_Call {
	return &Redis_Set_Call{Call: _e.mock.On("Set", key, value)}
}

func (_c *Redis_Set_Call) Run(run func(key string, value interface{})) *Redis_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Redis_Set_Call) Return(err error) *Redis_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Redis_Set_Call) RunAndReturn(run func(key string, value interface{}) error) *Redis_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetWithExpiration provides a mock function for the type Redis
func (_mock *Redis) SetWithExpiration(key string, value interface{}, expiration time.Duration) error {
	ret := _mock.Called(key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for SetWithExpiration")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, time.Duration) error); ok {
		r0 = returnFunc(key, value, expiration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Redis_SetWithExpiration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWithExpiration'
type Redis_SetWithExpiration_Call struct {
	*mock.Call
}

// SetWithExpiration is a helper method to define mock.On call
//   - key string
//   - value interface{}
//   - expiration time.Duration
func (_e *Redis_Expecter) SetWithExpiration(key interface{}, value interface{}, expiration interface{}) *Redis_SetWithExpiration_Call {
	return &Redis_SetWithExpiration_Call{Call: _e.mock.On("SetWithExpiration", key, value, expiration)}
}

func (_c *Redis_SetWithExpiration_Call) Run(run func(key string, value interface{}, expiration time.Duration)) *Redis_SetWithExpiration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Redis_SetWithExpiration_Call) Return(err error) *Redis_SetWithExpiration_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Redis_SetWithExpiration_Call) RunAndReturn(run func(key string, value interface{}, expiration time.Duration) error) *Redis_SetWithExpiration_Call {
	_c.Call.Return(run)
	return _c
}
