// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewNotifier creates a new instance of Notifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Notifier {
	mock := &Notifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Notifier is an autogenerated mock type for the Notifier type
type Notifier struct {
	mock.Mock
}

type Notifier_Expecter struct {
	mock *mock.Mock
}

func (_m *Notifier) EXPECT() *Notifier_Expecter {
	return &Notifier_Expecter{mock: &_m.Mock}
}

// SendOrderPlaced provides a mock function for the type Notifier
func (_mock *Notifier) SendOrderPlaced(ctx context.Context, orderID string, userEmail string) error {
	ret := _mock.Called(ctx, orderID, userEmail)

	if len(ret) == 0 {
		panic("no return value specified for SendOrderPlaced")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, orderID, userEmail)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Notifier_SendOrderPlaced_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendOrderPlaced'
type Notifier_SendOrderPlaced_Call struct {
	*mock.Call
}

// SendOrderPlaced is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - userEmail string
func (_e *Notifier_Expecter) SendOrderPlaced(ctx interface{}, orderID interface{}, userEmail interface{}) *Notifier_SendOrderPlaced_Call {
	return &Notifier_SendOrderPlaced_Call{Call: _e.mock.On("SendOrderPlaced", ctx, orderID, userEmail)}
}

func (_c *Notifier_SendOrderPlaced_Call) Run(run func(ctx context.Context, orderID string, userEmail string)) *Notifier_SendOrderPlaced_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Notifier_SendOrderPlaced_Call) Return(err error) *Notifier_SendOrderPlaced_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Notifier_SendOrderPlaced_Call) RunAndReturn(run func(ctx context.Context, orderID string, userEmail string) error) *Notifier_SendOrderPlaced_Call {
	_c.Call.Return(run)
	return _c
}

// SendOrderStatusChanged provides a mock function for the type Notifier
func (_mock *Notifier) SendOrderStatusChanged(ctx context.Context, orderID string, userEmail string, newStatus string) error {
	ret := _mock.Called(ctx, orderID, userEmail, newStatus)

	if len(ret) == 0 {
		panic("no return value specified for SendOrderStatusChanged")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, orderID, userEmail, newStatus)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Notifier_SendOrderStatusChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendOrderStatusChanged'
type Notifier_SendOrderStatusChanged_Call struct {
	*mock.Call
}

// SendOrderStatusChanged is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - userEmail string
//   - newStatus string
func (_e *Notifier_Expecter) SendOrderStatusChanged(ctx interface{}, orderID interface{}, userEmail interface{}, newStatus interface{}) *Notifier_SendOrderStatusChanged_Call {
	return &Notifier_SendOrderStatusChanged_Call{Call: _e.mock.On("SendOrderStatusChanged", ctx, orderID, userEmail, newStatus)}
}

func (_c *Notifier_SendOrderStatusChanged_Call) Run(run func(ctx context.Context, orderID string, userEmail string, newStatus string)) *Notifier_SendOrderStatusChanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Notifier_SendOrderStatusChanged_Call) Return(err error) *Notifier_SendOrderStatusChanged_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Notifier_SendOrderStatusChanged_Call) RunAndReturn(run func(ctx context.Context, orderID string, userEmail string, newStatus string) error) *Notifier_SendOrderStatusChanged_Call {
	_c.Call.Return(run)
	return _c
}
