// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"goshop/internal/cart/model"

	mock "github.com/stretchr/testify/mock"
)

// NewCartRepository creates a new instance of CartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CartRepository {
	mock := &CartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CartRepository is an autogenerated mock type for the CartRepository type
type CartRepository struct {
	mock.Mock
}

type CartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CartRepository) EXPECT() *CartRepository_Expecter {
	return &CartRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type CartRepository
func (_mock *CartRepository) Create(ctx context.Context, cart *model.Cart) error {
	ret := _mock.Called(ctx, cart)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Cart) error); ok {
		r0 = returnFunc(ctx, cart)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CartRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CartRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cart *model.Cart
func (_e *CartRepository_Expecter) Create(ctx interface{}, cart interface{}) *CartRepository_Create_Call {
	return &CartRepository_Create_Call{Call: _e.mock.On("Create", ctx, cart)}
}

func (_c *CartRepository_Create_Call) Run(run func(ctx context.Context, cart *model.Cart)) *CartRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Cart
		if args[1] != nil {
			arg1 = args[1].(*model.Cart)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CartRepository_Create_Call) Return(err error) *CartRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CartRepository_Create_Call) RunAndReturn(run func(ctx context.Context, cart *model.Cart) error) *CartRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetCartByUserID provides a mock function for the type CartRepository
func (_mock *CartRepository) GetCartByUserID(ctx context.Context, userID string) (*model.Cart, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCartByUserID")
	}

	var r0 *model.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Cart, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Cart); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Cart)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CartRepository_GetCartByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCartByUserID'
type CartRepository_GetCartByUserID_Call struct {
	*mock.Call
}

// GetCartByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *CartRepository_Expecter) GetCartByUserID(ctx interface{}, userID interface{}) *CartRepository_GetCartByUserID_Call {
	return &CartRepository_GetCartByUserID_Call{Call: _e.mock.On("GetCartByUserID", ctx, userID)}
}

func (_c *CartRepository_GetCartByUserID_Call) Run(run func(ctx context.Context, userID string)) *CartRepository_GetCartByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CartRepository_GetCartByUserID_Call) Return(cart *model.Cart, err error) *CartRepository_GetCartByUserID_Call {
	_c.Call.Return(cart, err)
	return _c
}

func (_c *CartRepository_GetCartByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) (*model.Cart, error)) *CartRepository_GetCartByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type CartRepository
func (_mock *CartRepository) Update(ctx context.Context, cart *model.Cart) error {
	ret := _mock.Called(ctx, cart)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Cart) error); ok {
		r0 = returnFunc(ctx, cart)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CartRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CartRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - cart *model.Cart
func (_e *CartRepository_Expecter) Update(ctx interface{}, cart interface{}) *CartRepository_Update_Call {
	return &CartRepository_Update_Call{Call: _e.mock.On("Update", ctx, cart)}
}

func (_c *CartRepository_Update_Call) Run(run func(ctx context.Context, cart *model.Cart)) *CartRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Cart
		if args[1] != nil {
			arg1 = args[1].(*model.Cart)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CartRepository_Update_Call) Return(err error) *CartRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CartRepository_Update_Call) RunAndReturn(run func(ctx context.Context, cart *model.Cart) error) *CartRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
