// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"
	model "goshop/internal/cart/model"

	mock "github.com/stretchr/testify/mock"
)

// CartRepository is an autogenerated mock type for the CartRepository type
type CartRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, cart
func (_m *CartRepository) Create(ctx context.Context, cart *model.Cart) error {
	ret := _m.Called(ctx, cart)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Cart) error); ok {
		r0 = rf(ctx, cart)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCartByUserID provides a mock function with given fields: ctx, userID
func (_m *CartRepository) GetCartByUserID(ctx context.Context, userID string) (*model.Cart, error) {
	ret := _m.Called(ctx, userID)

	var r0 *model.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Cart, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Cart); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, cart
func (_m *CartRepository) Update(ctx context.Context, cart *model.Cart) error {
	ret := _m.Called(ctx, cart)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Cart) error); ok {
		r0 = rf(ctx, cart)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCartRepository creates a new instance of CartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CartRepository {
	mock := &CartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
