// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"goshop/internal/product/dto"
	"goshop/internal/product/model"

	mock "github.com/stretchr/testify/mock"
)

// NewCategoryService creates a new instance of CategoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryService {
	mock := &CategoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CategoryService is an autogenerated mock type for the CategoryService type
type CategoryService struct {
	mock.Mock
}

type CategoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *CategoryService) EXPECT() *CategoryService_Expecter {
	return &CategoryService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type CategoryService
func (_mock *CategoryService) Create(ctx context.Context, req *dto.CreateCategoryReq) (*model.Category, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.CreateCategoryReq) (*model.Category, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.CreateCategoryReq) *model.Category); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.CreateCategoryReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoryService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CategoryService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.CreateCategoryReq
func (_e *CategoryService_Expecter) Create(ctx interface{}, req interface{}) *CategoryService_Create_Call {
	return &CategoryService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *CategoryService_Create_Call) Run(run func(ctx context.Context, req *dto.CreateCategoryReq)) *CategoryService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.CreateCategoryReq
		if args[1] != nil {
			arg1 = args[1].(*dto.CreateCategoryReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CategoryService_Create_Call) Return(category *model.Category, err error) *CategoryService_Create_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *CategoryService_Create_Call) RunAndReturn(run func(ctx context.Context, req *dto.CreateCategoryReq) (*model.Category, error)) *CategoryService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type CategoryService
func (_mock *CategoryService) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CategoryService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CategoryService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *CategoryService_Expecter) Delete(ctx interface{}, id interface{}) *CategoryService_Delete_Call {
	return &CategoryService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *CategoryService_Delete_Call) Run(run func(ctx context.Context, id string)) *CategoryService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CategoryService_Delete_Call) Return(err error) *CategoryService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CategoryService_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *CategoryService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetCategoryByID provides a mock function for the type CategoryService
func (_mock *CategoryService) GetCategoryByID(ctx context.Context, id string) (*model.Category, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoryByID")
	}

	var r0 *model.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Category, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Category); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoryService_GetCategoryByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategoryByID'
type CategoryService_GetCategoryByID_Call struct {
	*mock.Call
}

// GetCategoryByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *CategoryService_Expecter) GetCategoryByID(ctx interface{}, id interface{}) *CategoryService_GetCategoryByID_Call {
	return &CategoryService_GetCategoryByID_Call{Call: _e.mock.On("GetCategoryByID", ctx, id)}
}

func (_c *CategoryService_GetCategoryByID_Call) Run(run func(ctx context.Context, id string)) *CategoryService_GetCategoryByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CategoryService_GetCategoryByID_Call) Return(category *model.Category, err error) *CategoryService_GetCategoryByID_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *CategoryService_GetCategoryByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Category, error)) *CategoryService_GetCategoryByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListCategories provides a mock function for the type CategoryService
func (_mock *CategoryService) ListCategories(ctx context.Context) ([]*model.Category, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 []*model.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*model.Category, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*model.Category); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoryService_ListCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCategories'
type CategoryService_ListCategories_Call struct {
	*mock.Call
}

// ListCategories is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CategoryService_Expecter) ListCategories(ctx interface{}) *CategoryService_ListCategories_Call {
	return &CategoryService_ListCategories_Call{Call: _e.mock.On("ListCategories", ctx)}
}

func (_c *CategoryService_ListCategories_Call) Run(run func(ctx context.Context)) *CategoryService_ListCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CategoryService_ListCategories_Call) Return(categorys []*model.Category, err error) *CategoryService_ListCategories_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *CategoryService_ListCategories_Call) RunAndReturn(run func(ctx context.Context) ([]*model.Category, error)) *CategoryService_ListCategories_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type CategoryService
func (_mock *CategoryService) Update(ctx context.Context, id string, req *dto.UpdateCategoryReq) (*model.Category, error) {
	ret := _mock.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *dto.UpdateCategoryReq) (*model.Category, error)); ok {
		return returnFunc(ctx, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *dto.UpdateCategoryReq) *model.Category); ok {
		r0 = returnFunc(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *dto.UpdateCategoryReq) error); ok {
		r1 = returnFunc(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoryService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CategoryService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req *dto.UpdateCategoryReq
func (_e *CategoryService_Expecter) Update(ctx interface{}, id interface{}, req interface{}) *CategoryService_Update_Call {
	return &CategoryService_Update_Call{Call: _e.mock.On("Update", ctx, id, req)}
}

func (_c *CategoryService_Update_Call) Run(run func(ctx context.Context, id string, req *dto.UpdateCategoryReq)) *CategoryService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *dto.UpdateCategoryReq
		if args[2] != nil {
			arg2 = args[2].(*dto.UpdateCategoryReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CategoryService_Update_Call) Return(category *model.Category, err error) *CategoryService_Update_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *CategoryService_Update_Call) RunAndReturn(run func(ctx context.Context, id string, req *dto.UpdateCategoryReq) (*model.Category, error)) *CategoryService_Update_Call {
	_c.Call.Return(run)
	return _c
}
