// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"goshop/internal/product/domain"
	"goshop/internal/product/model"
	"goshop/pkg/paging"

	mock "github.com/stretchr/testify/mock"
)

// NewProductService creates a new instance of ProductService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductService {
	mock := &ProductService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProductService is an autogenerated mock type for the ProductService type
type ProductService struct {
	mock.Mock
}

type ProductService_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductService) EXPECT() *ProductService_Expecter {
	return &ProductService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type ProductService
func (_mock *ProductService) Create(ctx context.Context, req *domain.CreateProductReq) (*model.Product, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.CreateProductReq) (*model.Product, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.CreateProductReq) *model.Product); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.CreateProductReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ProductService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.CreateProductReq
func (_e *ProductService_Expecter) Create(ctx interface{}, req interface{}) *ProductService_Create_Call {
	return &ProductService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *ProductService_Create_Call) Run(run func(ctx context.Context, req *domain.CreateProductReq)) *ProductService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.CreateProductReq
		if args[1] != nil {
			arg1 = args[1].(*domain.CreateProductReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductService_Create_Call) Return(product *model.Product, err error) *ProductService_Create_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *ProductService_Create_Call) RunAndReturn(run func(ctx context.Context, req *domain.CreateProductReq) (*model.Product, error)) *ProductService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductByID provides a mock function for the type ProductService
func (_mock *ProductService) GetProductByID(ctx context.Context, id string) (*model.Product, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 *model.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Product, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Product); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductService_GetProductByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductByID'
type ProductService_GetProductByID_Call struct {
	*mock.Call
}

// GetProductByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ProductService_Expecter) GetProductByID(ctx interface{}, id interface{}) *ProductService_GetProductByID_Call {
	return &ProductService_GetProductByID_Call{Call: _e.mock.On("GetProductByID", ctx, id)}
}

func (_c *ProductService_GetProductByID_Call) Run(run func(ctx context.Context, id string)) *ProductService_GetProductByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductService_GetProductByID_Call) Return(product *model.Product, err error) *ProductService_GetProductByID_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *ProductService_GetProductByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Product, error)) *ProductService_GetProductByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListProducts provides a mock function for the type ProductService
func (_mock *ProductService) ListProducts(c context.Context, req *domain.ListProductReq) ([]*model.Product, *paging.Pagination, error) {
	ret := _mock.Called(c, req)

	if len(ret) == 0 {
		panic("no return value specified for ListProducts")
	}

	var r0 []*model.Product
	var r1 *paging.Pagination
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.ListProductReq) ([]*model.Product, *paging.Pagination, error)); ok {
		return returnFunc(c, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.ListProductReq) []*model.Product); ok {
		r0 = returnFunc(c, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.ListProductReq) *paging.Pagination); ok {
		r1 = returnFunc(c, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*paging.Pagination)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *domain.ListProductReq) error); ok {
		r2 = returnFunc(c, req)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// ProductService_ListProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProducts'
type ProductService_ListProducts_Call struct {
	*mock.Call
}

// ListProducts is a helper method to define mock.On call
//   - c context.Context
//   - req *dto.ListProductReq
func (_e *ProductService_Expecter) ListProducts(c interface{}, req interface{}) *ProductService_ListProducts_Call {
	return &ProductService_ListProducts_Call{Call: _e.mock.On("ListProducts", c, req)}
}

func (_c *ProductService_ListProducts_Call) Run(run func(c context.Context, req *domain.ListProductReq)) *ProductService_ListProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.ListProductReq
		if args[1] != nil {
			arg1 = args[1].(*domain.ListProductReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductService_ListProducts_Call) Return(products []*model.Product, pagination *paging.Pagination, err error) *ProductService_ListProducts_Call {
	_c.Call.Return(products, pagination, err)
	return _c
}

func (_c *ProductService_ListProducts_Call) RunAndReturn(run func(c context.Context, req *domain.ListProductReq) ([]*model.Product, *paging.Pagination, error)) *ProductService_ListProducts_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type ProductService
func (_mock *ProductService) Update(ctx context.Context, id string, req *domain.UpdateProductReq) (*model.Product, error) {
	ret := _mock.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *domain.UpdateProductReq) (*model.Product, error)); ok {
		return returnFunc(ctx, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *domain.UpdateProductReq) *model.Product); ok {
		r0 = returnFunc(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *domain.UpdateProductReq) error); ok {
		r1 = returnFunc(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ProductService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req *dto.UpdateProductReq
func (_e *ProductService_Expecter) Update(ctx interface{}, id interface{}, req interface{}) *ProductService_Update_Call {
	return &ProductService_Update_Call{Call: _e.mock.On("Update", ctx, id, req)}
}

func (_c *ProductService_Update_Call) Run(run func(ctx context.Context, id string, req *domain.UpdateProductReq)) *ProductService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *domain.UpdateProductReq
		if args[2] != nil {
			arg2 = args[2].(*domain.UpdateProductReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProductService_Update_Call) Return(product *model.Product, err error) *ProductService_Update_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *ProductService_Update_Call) RunAndReturn(run func(ctx context.Context, id string, req *domain.UpdateProductReq) (*model.Product, error)) *ProductService_Update_Call {
	_c.Call.Return(run)
	return _c
}
