// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"goshop/internal/product/domain"
	"goshop/internal/product/model"
	"goshop/pkg/paging"

	mock "github.com/stretchr/testify/mock"
)

// NewReviewService creates a new instance of ReviewService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReviewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReviewService {
	mock := &ReviewService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ReviewService is an autogenerated mock type for the ReviewService type
type ReviewService struct {
	mock.Mock
}

type ReviewService_Expecter struct {
	mock *mock.Mock
}

func (_m *ReviewService) EXPECT() *ReviewService_Expecter {
	return &ReviewService_Expecter{mock: &_m.Mock}
}

// CreateReview provides a mock function for the type ReviewService
func (_mock *ReviewService) CreateReview(ctx context.Context, productID string, userID string, req *domain.CreateReviewReq) (*model.Review, error) {
	ret := _mock.Called(ctx, productID, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateReview")
	}

	var r0 *model.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *domain.CreateReviewReq) (*model.Review, error)); ok {
		return returnFunc(ctx, productID, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *domain.CreateReviewReq) *model.Review); ok {
		r0 = returnFunc(ctx, productID, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *domain.CreateReviewReq) error); ok {
		r1 = returnFunc(ctx, productID, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ReviewService_CreateReview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReview'
type ReviewService_CreateReview_Call struct {
	*mock.Call
}

// CreateReview is a helper method to define mock.On call
//   - ctx context.Context
//   - productID string
//   - userID string
//   - req *dto.CreateReviewReq
func (_e *ReviewService_Expecter) CreateReview(ctx interface{}, productID interface{}, userID interface{}, req interface{}) *ReviewService_CreateReview_Call {
	return &ReviewService_CreateReview_Call{Call: _e.mock.On("CreateReview", ctx, productID, userID, req)}
}

func (_c *ReviewService_CreateReview_Call) Run(run func(ctx context.Context, productID string, userID string, req *domain.CreateReviewReq)) *ReviewService_CreateReview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *domain.CreateReviewReq
		if args[3] != nil {
			arg3 = args[3].(*domain.CreateReviewReq)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ReviewService_CreateReview_Call) Return(review *model.Review, err error) *ReviewService_CreateReview_Call {
	_c.Call.Return(review, err)
	return _c
}

func (_c *ReviewService_CreateReview_Call) RunAndReturn(run func(ctx context.Context, productID string, userID string, req *domain.CreateReviewReq) (*model.Review, error)) *ReviewService_CreateReview_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteReview provides a mock function for the type ReviewService
func (_mock *ReviewService) DeleteReview(ctx context.Context, id string, userID string) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReview")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ReviewService_DeleteReview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteReview'
type ReviewService_DeleteReview_Call struct {
	*mock.Call
}

// DeleteReview is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *ReviewService_Expecter) DeleteReview(ctx interface{}, id interface{}, userID interface{}) *ReviewService_DeleteReview_Call {
	return &ReviewService_DeleteReview_Call{Call: _e.mock.On("DeleteReview", ctx, id, userID)}
}

func (_c *ReviewService_DeleteReview_Call) Run(run func(ctx context.Context, id string, userID string)) *ReviewService_DeleteReview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ReviewService_DeleteReview_Call) Return(err error) *ReviewService_DeleteReview_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ReviewService_DeleteReview_Call) RunAndReturn(run func(ctx context.Context, id string, userID string) error) *ReviewService_DeleteReview_Call {
	_c.Call.Return(run)
	return _c
}

// ListReviews provides a mock function for the type ReviewService
func (_mock *ReviewService) ListReviews(ctx context.Context, productID string, page int64, limit int64) ([]*model.Review, *paging.Pagination, error) {
	ret := _mock.Called(ctx, productID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListReviews")
	}

	var r0 []*model.Review
	var r1 *paging.Pagination
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]*model.Review, *paging.Pagination, error)); ok {
		return returnFunc(ctx, productID, page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) []*model.Review); ok {
		r0 = returnFunc(ctx, productID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, int64) *paging.Pagination); ok {
		r1 = returnFunc(ctx, productID, page, limit)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*paging.Pagination)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, int64, int64) error); ok {
		r2 = returnFunc(ctx, productID, page, limit)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// ReviewService_ListReviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReviews'
type ReviewService_ListReviews_Call struct {
	*mock.Call
}

// ListReviews is a helper method to define mock.On call
//   - ctx context.Context
//   - productID string
//   - page int64
//   - limit int64
func (_e *ReviewService_Expecter) ListReviews(ctx interface{}, productID interface{}, page interface{}, limit interface{}) *ReviewService_ListReviews_Call {
	return &ReviewService_ListReviews_Call{Call: _e.mock.On("ListReviews", ctx, productID, page, limit)}
}

func (_c *ReviewService_ListReviews_Call) Run(run func(ctx context.Context, productID string, page int64, limit int64)) *ReviewService_ListReviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ReviewService_ListReviews_Call) Return(reviews []*model.Review, pagination *paging.Pagination, err error) *ReviewService_ListReviews_Call {
	_c.Call.Return(reviews, pagination, err)
	return _c
}

func (_c *ReviewService_ListReviews_Call) RunAndReturn(run func(ctx context.Context, productID string, page int64, limit int64) ([]*model.Review, *paging.Pagination, error)) *ReviewService_ListReviews_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateReview provides a mock function for the type ReviewService
func (_mock *ReviewService) UpdateReview(ctx context.Context, id string, userID string, req *domain.UpdateReviewReq) (*model.Review, error) {
	ret := _mock.Called(ctx, id, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReview")
	}

	var r0 *model.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *domain.UpdateReviewReq) (*model.Review, error)); ok {
		return returnFunc(ctx, id, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *domain.UpdateReviewReq) *model.Review); ok {
		r0 = returnFunc(ctx, id, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *domain.UpdateReviewReq) error); ok {
		r1 = returnFunc(ctx, id, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ReviewService_UpdateReview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateReview'
type ReviewService_UpdateReview_Call struct {
	*mock.Call
}

// UpdateReview is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
//   - req *dto.UpdateReviewReq
func (_e *ReviewService_Expecter) UpdateReview(ctx interface{}, id interface{}, userID interface{}, req interface{}) *ReviewService_UpdateReview_Call {
	return &ReviewService_UpdateReview_Call{Call: _e.mock.On("UpdateReview", ctx, id, userID, req)}
}

func (_c *ReviewService_UpdateReview_Call) Run(run func(ctx context.Context, id string, userID string, req *domain.UpdateReviewReq)) *ReviewService_UpdateReview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *domain.UpdateReviewReq
		if args[3] != nil {
			arg3 = args[3].(*domain.UpdateReviewReq)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ReviewService_UpdateReview_Call) Return(review *model.Review, err error) *ReviewService_UpdateReview_Call {
	_c.Call.Return(review, err)
	return _c
}

func (_c *ReviewService_UpdateReview_Call) RunAndReturn(run func(ctx context.Context, id string, userID string, req *domain.UpdateReviewReq) (*model.Review, error)) *ReviewService_UpdateReview_Call {
	_c.Call.Return(run)
	return _c
}
