// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"goshop/internal/product/model"

	mock "github.com/stretchr/testify/mock"
)

// NewCategoryRepository creates a new instance of CategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryRepository {
	mock := &CategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CategoryRepository is an autogenerated mock type for the CategoryRepository type
type CategoryRepository struct {
	mock.Mock
}

type CategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CategoryRepository) EXPECT() *CategoryRepository_Expecter {
	return &CategoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type CategoryRepository
func (_mock *CategoryRepository) Create(ctx context.Context, category *model.Category) error {
	ret := _mock.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Category) error); ok {
		r0 = returnFunc(ctx, category)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CategoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CategoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - category *model.Category
func (_e *CategoryRepository_Expecter) Create(ctx interface{}, category interface{}) *CategoryRepository_Create_Call {
	return &CategoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, category)}
}

func (_c *CategoryRepository_Create_Call) Run(run func(ctx context.Context, category *model.Category)) *CategoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Category
		if args[1] != nil {
			arg1 = args[1].(*model.Category)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CategoryRepository_Create_Call) Return(err error) *CategoryRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CategoryRepository_Create_Call) RunAndReturn(run func(ctx context.Context, category *model.Category) error) *CategoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type CategoryRepository
func (_mock *CategoryRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CategoryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CategoryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *CategoryRepository_Expecter) Delete(ctx interface{}, id interface{}) *CategoryRepository_Delete_Call {
	return &CategoryRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *CategoryRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *CategoryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CategoryRepository_Delete_Call) Return(err error) *CategoryRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CategoryRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *CategoryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type CategoryRepository
func (_mock *CategoryRepository) GetByID(ctx context.Context, id string) (*model.Category, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Category, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Category); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoryRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type CategoryRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *CategoryRepository_Expecter) GetByID(ctx interface{}, id interface{}) *CategoryRepository_GetByID_Call {
	return &CategoryRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *CategoryRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *CategoryRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CategoryRepository_GetByID_Call) Return(category *model.Category, err error) *CategoryRepository_GetByID_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *CategoryRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Category, error)) *CategoryRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type CategoryRepository
func (_mock *CategoryRepository) List(ctx context.Context) ([]*model.Category, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*model.Category, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*model.Category); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CategoryRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type CategoryRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CategoryRepository_Expecter) List(ctx interface{}) *CategoryRepository_List_Call {
	return &CategoryRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *CategoryRepository_List_Call) Run(run func(ctx context.Context)) *CategoryRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CategoryRepository_List_Call) Return(categorys []*model.Category, err error) *CategoryRepository_List_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *CategoryRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]*model.Category, error)) *CategoryRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type CategoryRepository
func (_mock *CategoryRepository) Update(ctx context.Context, category *model.Category) error {
	ret := _mock.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Category) error); ok {
		r0 = returnFunc(ctx, category)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CategoryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CategoryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - category *model.Category
func (_e *CategoryRepository_Expecter) Update(ctx interface{}, category interface{}) *CategoryRepository_Update_Call {
	return &CategoryRepository_Update_Call{Call: _e.mock.On("Update", ctx, category)}
}

func (_c *CategoryRepository_Update_Call) Run(run func(ctx context.Context, category *model.Category)) *CategoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Category
		if args[1] != nil {
			arg1 = args[1].(*model.Category)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CategoryRepository_Update_Call) Return(err error) *CategoryRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CategoryRepository_Update_Call) RunAndReturn(run func(ctx context.Context, category *model.Category) error) *CategoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
