// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"goshop/internal/product/domain"
	"goshop/internal/product/model"
	"goshop/pkg/paging"

	mock "github.com/stretchr/testify/mock"
)

// NewProductRepository creates a new instance of ProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductRepository {
	mock := &ProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProductRepository is an autogenerated mock type for the ProductRepository type
type ProductRepository struct {
	mock.Mock
}

type ProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductRepository) EXPECT() *ProductRepository_Expecter {
	return &ProductRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type ProductRepository
func (_mock *ProductRepository) Create(ctx context.Context, product *model.Product) error {
	ret := _mock.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Product) error); ok {
		r0 = returnFunc(ctx, product)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProductRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ProductRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - product *model.Product
func (_e *ProductRepository_Expecter) Create(ctx interface{}, product interface{}) *ProductRepository_Create_Call {
	return &ProductRepository_Create_Call{Call: _e.mock.On("Create", ctx, product)}
}

func (_c *ProductRepository_Create_Call) Run(run func(ctx context.Context, product *model.Product)) *ProductRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Product
		if args[1] != nil {
			arg1 = args[1].(*model.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductRepository_Create_Call) Return(err error) *ProductRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProductRepository_Create_Call) RunAndReturn(run func(ctx context.Context, product *model.Product) error) *ProductRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DecrementStock provides a mock function for the type ProductRepository
func (_mock *ProductRepository) DecrementStock(ctx context.Context, id string, qty int) error {
	ret := _mock.Called(ctx, id, qty)

	if len(ret) == 0 {
		panic("no return value specified for DecrementStock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = returnFunc(ctx, id, qty)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProductRepository_DecrementStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrementStock'
type ProductRepository_DecrementStock_Call struct {
	*mock.Call
}

// DecrementStock is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - qty int
func (_e *ProductRepository_Expecter) DecrementStock(ctx interface{}, id interface{}, qty interface{}) *ProductRepository_DecrementStock_Call {
	return &ProductRepository_DecrementStock_Call{Call: _e.mock.On("DecrementStock", ctx, id, qty)}
}

func (_c *ProductRepository_DecrementStock_Call) Run(run func(ctx context.Context, id string, qty int)) *ProductRepository_DecrementStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ProductRepository_DecrementStock_Call) Return(err error) *ProductRepository_DecrementStock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProductRepository_DecrementStock_Call) RunAndReturn(run func(ctx context.Context, id string, qty int) error) *ProductRepository_DecrementStock_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductByID provides a mock function for the type ProductRepository
func (_mock *ProductRepository) GetProductByID(ctx context.Context, id string) (*model.Product, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 *model.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Product, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Product); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductRepository_GetProductByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductByID'
type ProductRepository_GetProductByID_Call struct {
	*mock.Call
}

// GetProductByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ProductRepository_Expecter) GetProductByID(ctx interface{}, id interface{}) *ProductRepository_GetProductByID_Call {
	return &ProductRepository_GetProductByID_Call{Call: _e.mock.On("GetProductByID", ctx, id)}
}

func (_c *ProductRepository_GetProductByID_Call) Run(run func(ctx context.Context, id string)) *ProductRepository_GetProductByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductRepository_GetProductByID_Call) Return(product *model.Product, err error) *ProductRepository_GetProductByID_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *ProductRepository_GetProductByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Product, error)) *ProductRepository_GetProductByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListProducts provides a mock function for the type ProductRepository
func (_mock *ProductRepository) ListProducts(ctx context.Context, req *domain.ListProductReq) ([]*model.Product, *paging.Pagination, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListProducts")
	}

	var r0 []*model.Product
	var r1 *paging.Pagination
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.ListProductReq) ([]*model.Product, *paging.Pagination, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.ListProductReq) []*model.Product); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.ListProductReq) *paging.Pagination); ok {
		r1 = returnFunc(ctx, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*paging.Pagination)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *domain.ListProductReq) error); ok {
		r2 = returnFunc(ctx, req)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// ProductRepository_ListProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProducts'
type ProductRepository_ListProducts_Call struct {
	*mock.Call
}

// ListProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.ListProductReq
func (_e *ProductRepository_Expecter) ListProducts(ctx interface{}, req interface{}) *ProductRepository_ListProducts_Call {
	return &ProductRepository_ListProducts_Call{Call: _e.mock.On("ListProducts", ctx, req)}
}

func (_c *ProductRepository_ListProducts_Call) Run(run func(ctx context.Context, req *domain.ListProductReq)) *ProductRepository_ListProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.ListProductReq
		if args[1] != nil {
			arg1 = args[1].(*domain.ListProductReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductRepository_ListProducts_Call) Return(products []*model.Product, pagination *paging.Pagination, err error) *ProductRepository_ListProducts_Call {
	_c.Call.Return(products, pagination, err)
	return _c
}

func (_c *ProductRepository_ListProducts_Call) RunAndReturn(run func(ctx context.Context, req *domain.ListProductReq) ([]*model.Product, *paging.Pagination, error)) *ProductRepository_ListProducts_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type ProductRepository
func (_mock *ProductRepository) Update(ctx context.Context, product *model.Product) error {
	ret := _mock.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Product) error); ok {
		r0 = returnFunc(ctx, product)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProductRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ProductRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - product *model.Product
func (_e *ProductRepository_Expecter) Update(ctx interface{}, product interface{}) *ProductRepository_Update_Call {
	return &ProductRepository_Update_Call{Call: _e.mock.On("Update", ctx, product)}
}

func (_c *ProductRepository_Update_Call) Run(run func(ctx context.Context, product *model.Product)) *ProductRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Product
		if args[1] != nil {
			arg1 = args[1].(*model.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductRepository_Update_Call) Return(err error) *ProductRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProductRepository_Update_Call) RunAndReturn(run func(ctx context.Context, product *model.Product) error) *ProductRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRating provides a mock function for the type ProductRepository
func (_mock *ProductRepository) UpdateRating(ctx context.Context, id string, avgRating float64, reviewCount int) error {
	ret := _mock.Called(ctx, id, avgRating, reviewCount)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRating")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, float64, int) error); ok {
		r0 = returnFunc(ctx, id, avgRating, reviewCount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProductRepository_UpdateRating_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRating'
type ProductRepository_UpdateRating_Call struct {
	*mock.Call
}

// UpdateRating is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - avgRating float64
//   - reviewCount int
func (_e *ProductRepository_Expecter) UpdateRating(ctx interface{}, id interface{}, avgRating interface{}, reviewCount interface{}) *ProductRepository_UpdateRating_Call {
	return &ProductRepository_UpdateRating_Call{Call: _e.mock.On("UpdateRating", ctx, id, avgRating, reviewCount)}
}

func (_c *ProductRepository_UpdateRating_Call) Run(run func(ctx context.Context, id string, avgRating float64, reviewCount int)) *ProductRepository_UpdateRating_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ProductRepository_UpdateRating_Call) Return(err error) *ProductRepository_UpdateRating_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProductRepository_UpdateRating_Call) RunAndReturn(run func(ctx context.Context, id string, avgRating float64, reviewCount int) error) *ProductRepository_UpdateRating_Call {
	_c.Call.Return(run)
	return _c
}
