// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"goshop/internal/product/model"
	"goshop/pkg/paging"

	mock "github.com/stretchr/testify/mock"
)

// NewReviewRepository creates a new instance of ReviewRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReviewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReviewRepository {
	mock := &ReviewRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ReviewRepository is an autogenerated mock type for the ReviewRepository type
type ReviewRepository struct {
	mock.Mock
}

type ReviewRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ReviewRepository) EXPECT() *ReviewRepository_Expecter {
	return &ReviewRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type ReviewRepository
func (_mock *ReviewRepository) Create(ctx context.Context, review *model.Review) error {
	ret := _mock.Called(ctx, review)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Review) error); ok {
		r0 = returnFunc(ctx, review)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ReviewRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ReviewRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - review *model.Review
func (_e *ReviewRepository_Expecter) Create(ctx interface{}, review interface{}) *ReviewRepository_Create_Call {
	return &ReviewRepository_Create_Call{Call: _e.mock.On("Create", ctx, review)}
}

func (_c *ReviewRepository_Create_Call) Run(run func(ctx context.Context, review *model.Review)) *ReviewRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Review
		if args[1] != nil {
			arg1 = args[1].(*model.Review)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ReviewRepository_Create_Call) Return(err error) *ReviewRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ReviewRepository_Create_Call) RunAndReturn(run func(ctx context.Context, review *model.Review) error) *ReviewRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type ReviewRepository
func (_mock *ReviewRepository) Delete(ctx context.Context, id string, userID string) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ReviewRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ReviewRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *ReviewRepository_Expecter) Delete(ctx interface{}, id interface{}, userID interface{}) *ReviewRepository_Delete_Call {
	return &ReviewRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id, userID)}
}

func (_c *ReviewRepository_Delete_Call) Run(run func(ctx context.Context, id string, userID string)) *ReviewRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ReviewRepository_Delete_Call) Return(err error) *ReviewRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ReviewRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string, userID string) error) *ReviewRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAggregates provides a mock function for the type ReviewRepository
func (_mock *ReviewRepository) GetAggregates(ctx context.Context, productID string) (float64, int, error) {
	ret := _mock.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetAggregates")
	}

	var r0 float64
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (float64, int, error)); ok {
		return returnFunc(ctx, productID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) float64); ok {
		r0 = returnFunc(ctx, productID)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) int); ok {
		r1 = returnFunc(ctx, productID)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, productID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// ReviewRepository_GetAggregates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAggregates'
type ReviewRepository_GetAggregates_Call struct {
	*mock.Call
}

// GetAggregates is a helper method to define mock.On call
//   - ctx context.Context
//   - productID string
func (_e *ReviewRepository_Expecter) GetAggregates(ctx interface{}, productID interface{}) *ReviewRepository_GetAggregates_Call {
	return &ReviewRepository_GetAggregates_Call{Call: _e.mock.On("GetAggregates", ctx, productID)}
}

func (_c *ReviewRepository_GetAggregates_Call) Run(run func(ctx context.Context, productID string)) *ReviewRepository_GetAggregates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ReviewRepository_GetAggregates_Call) Return(avgRating float64, count int, err error) *ReviewRepository_GetAggregates_Call {
	_c.Call.Return(avgRating, count, err)
	return _c
}

func (_c *ReviewRepository_GetAggregates_Call) RunAndReturn(run func(ctx context.Context, productID string) (float64, int, error)) *ReviewRepository_GetAggregates_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type ReviewRepository
func (_mock *ReviewRepository) GetByID(ctx context.Context, id string) (*model.Review, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Review, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Review); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ReviewRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ReviewRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ReviewRepository_Expecter) GetByID(ctx interface{}, id interface{}) *ReviewRepository_GetByID_Call {
	return &ReviewRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ReviewRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *ReviewRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ReviewRepository_GetByID_Call) Return(review *model.Review, err error) *ReviewRepository_GetByID_Call {
	_c.Call.Return(review, err)
	return _c
}

func (_c *ReviewRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Review, error)) *ReviewRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByProduct provides a mock function for the type ReviewRepository
func (_mock *ReviewRepository) ListByProduct(ctx context.Context, productID string, page int64, limit int64) ([]*model.Review, *paging.Pagination, error) {
	ret := _mock.Called(ctx, productID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListByProduct")
	}

	var r0 []*model.Review
	var r1 *paging.Pagination
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]*model.Review, *paging.Pagination, error)); ok {
		return returnFunc(ctx, productID, page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) []*model.Review); ok {
		r0 = returnFunc(ctx, productID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, int64) *paging.Pagination); ok {
		r1 = returnFunc(ctx, productID, page, limit)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*paging.Pagination)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, int64, int64) error); ok {
		r2 = returnFunc(ctx, productID, page, limit)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// ReviewRepository_ListByProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByProduct'
type ReviewRepository_ListByProduct_Call struct {
	*mock.Call
}

// ListByProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - productID string
//   - page int64
//   - limit int64
func (_e *ReviewRepository_Expecter) ListByProduct(ctx interface{}, productID interface{}, page interface{}, limit interface{}) *ReviewRepository_ListByProduct_Call {
	return &ReviewRepository_ListByProduct_Call{Call: _e.mock.On("ListByProduct", ctx, productID, page, limit)}
}

func (_c *ReviewRepository_ListByProduct_Call) Run(run func(ctx context.Context, productID string, page int64, limit int64)) *ReviewRepository_ListByProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ReviewRepository_ListByProduct_Call) Return(reviews []*model.Review, pagination *paging.Pagination, err error) *ReviewRepository_ListByProduct_Call {
	_c.Call.Return(reviews, pagination, err)
	return _c
}

func (_c *ReviewRepository_ListByProduct_Call) RunAndReturn(run func(ctx context.Context, productID string, page int64, limit int64) ([]*model.Review, *paging.Pagination, error)) *ReviewRepository_ListByProduct_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type ReviewRepository
func (_mock *ReviewRepository) Update(ctx context.Context, review *model.Review) error {
	ret := _mock.Called(ctx, review)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Review) error); ok {
		r0 = returnFunc(ctx, review)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ReviewRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ReviewRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - review *model.Review
func (_e *ReviewRepository_Expecter) Update(ctx interface{}, review interface{}) *ReviewRepository_Update_Call {
	return &ReviewRepository_Update_Call{Call: _e.mock.On("Update", ctx, review)}
}

func (_c *ReviewRepository_Update_Call) Run(run func(ctx context.Context, review *model.Review)) *ReviewRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Review
		if args[1] != nil {
			arg1 = args[1].(*model.Review)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ReviewRepository_Update_Call) Return(err error) *ReviewRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ReviewRepository_Update_Call) RunAndReturn(run func(ctx context.Context, review *model.Review) error) *ReviewRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
