// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"goshop/internal/user/dto"
	"goshop/internal/user/model"

	mock "github.com/stretchr/testify/mock"
)

// NewAddressService creates a new instance of AddressService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAddressService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AddressService {
	mock := &AddressService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AddressService is an autogenerated mock type for the AddressService type
type AddressService struct {
	mock.Mock
}

type AddressService_Expecter struct {
	mock *mock.Mock
}

func (_m *AddressService) EXPECT() *AddressService_Expecter {
	return &AddressService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type AddressService
func (_mock *AddressService) Create(ctx context.Context, userID string, req *dto.CreateAddressReq) (*model.Address, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Address
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *dto.CreateAddressReq) (*model.Address, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *dto.CreateAddressReq) *model.Address); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Address)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *dto.CreateAddressReq) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AddressService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type AddressService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req *dto.CreateAddressReq
func (_e *AddressService_Expecter) Create(ctx interface{}, userID interface{}, req interface{}) *AddressService_Create_Call {
	return &AddressService_Create_Call{Call: _e.mock.On("Create", ctx, userID, req)}
}

func (_c *AddressService_Create_Call) Run(run func(ctx context.Context, userID string, req *dto.CreateAddressReq)) *AddressService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *dto.CreateAddressReq
		if args[2] != nil {
			arg2 = args[2].(*dto.CreateAddressReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AddressService_Create_Call) Return(address *model.Address, err error) *AddressService_Create_Call {
	_c.Call.Return(address, err)
	return _c
}

func (_c *AddressService_Create_Call) RunAndReturn(run func(ctx context.Context, userID string, req *dto.CreateAddressReq) (*model.Address, error)) *AddressService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type AddressService
func (_mock *AddressService) Delete(ctx context.Context, id string, userID string) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AddressService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type AddressService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *AddressService_Expecter) Delete(ctx interface{}, id interface{}, userID interface{}) *AddressService_Delete_Call {
	return &AddressService_Delete_Call{Call: _e.mock.On("Delete", ctx, id, userID)}
}

func (_c *AddressService_Delete_Call) Run(run func(ctx context.Context, id string, userID string)) *AddressService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AddressService_Delete_Call) Return(err error) *AddressService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AddressService_Delete_Call) RunAndReturn(run func(ctx context.Context, id string, userID string) error) *AddressService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAddressByID provides a mock function for the type AddressService
func (_mock *AddressService) GetAddressByID(ctx context.Context, id string, userID string) (*model.Address, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAddressByID")
	}

	var r0 *model.Address
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.Address, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.Address); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Address)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AddressService_GetAddressByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAddressByID'
type AddressService_GetAddressByID_Call struct {
	*mock.Call
}

// GetAddressByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *AddressService_Expecter) GetAddressByID(ctx interface{}, id interface{}, userID interface{}) *AddressService_GetAddressByID_Call {
	return &AddressService_GetAddressByID_Call{Call: _e.mock.On("GetAddressByID", ctx, id, userID)}
}

func (_c *AddressService_GetAddressByID_Call) Run(run func(ctx context.Context, id string, userID string)) *AddressService_GetAddressByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AddressService_GetAddressByID_Call) Return(address *model.Address, err error) *AddressService_GetAddressByID_Call {
	_c.Call.Return(address, err)
	return _c
}

func (_c *AddressService_GetAddressByID_Call) RunAndReturn(run func(ctx context.Context, id string, userID string) (*model.Address, error)) *AddressService_GetAddressByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListAddresses provides a mock function for the type AddressService
func (_mock *AddressService) ListAddresses(ctx context.Context, userID string) ([]*model.Address, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListAddresses")
	}

	var r0 []*model.Address
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*model.Address, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*model.Address); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Address)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AddressService_ListAddresses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAddresses'
type AddressService_ListAddresses_Call struct {
	*mock.Call
}

// ListAddresses is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *AddressService_Expecter) ListAddresses(ctx interface{}, userID interface{}) *AddressService_ListAddresses_Call {
	return &AddressService_ListAddresses_Call{Call: _e.mock.On("ListAddresses", ctx, userID)}
}

func (_c *AddressService_ListAddresses_Call) Run(run func(ctx context.Context, userID string)) *AddressService_ListAddresses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AddressService_ListAddresses_Call) Return(addresss []*model.Address, err error) *AddressService_ListAddresses_Call {
	_c.Call.Return(addresss, err)
	return _c
}

func (_c *AddressService_ListAddresses_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*model.Address, error)) *AddressService_ListAddresses_Call {
	_c.Call.Return(run)
	return _c
}

// SetDefault provides a mock function for the type AddressService
func (_mock *AddressService) SetDefault(ctx context.Context, id string, userID string) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for SetDefault")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AddressService_SetDefault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDefault'
type AddressService_SetDefault_Call struct {
	*mock.Call
}

// SetDefault is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *AddressService_Expecter) SetDefault(ctx interface{}, id interface{}, userID interface{}) *AddressService_SetDefault_Call {
	return &AddressService_SetDefault_Call{Call: _e.mock.On("SetDefault", ctx, id, userID)}
}

func (_c *AddressService_SetDefault_Call) Run(run func(ctx context.Context, id string, userID string)) *AddressService_SetDefault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AddressService_SetDefault_Call) Return(err error) *AddressService_SetDefault_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AddressService_SetDefault_Call) RunAndReturn(run func(ctx context.Context, id string, userID string) error) *AddressService_SetDefault_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type AddressService
func (_mock *AddressService) Update(ctx context.Context, id string, userID string, req *dto.UpdateAddressReq) (*model.Address, error) {
	ret := _mock.Called(ctx, id, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Address
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *dto.UpdateAddressReq) (*model.Address, error)); ok {
		return returnFunc(ctx, id, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *dto.UpdateAddressReq) *model.Address); ok {
		r0 = returnFunc(ctx, id, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Address)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *dto.UpdateAddressReq) error); ok {
		r1 = returnFunc(ctx, id, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AddressService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type AddressService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
//   - req *dto.UpdateAddressReq
func (_e *AddressService_Expecter) Update(ctx interface{}, id interface{}, userID interface{}, req interface{}) *AddressService_Update_Call {
	return &AddressService_Update_Call{Call: _e.mock.On("Update", ctx, id, userID, req)}
}

func (_c *AddressService_Update_Call) Run(run func(ctx context.Context, id string, userID string, req *dto.UpdateAddressReq)) *AddressService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *dto.UpdateAddressReq
		if args[3] != nil {
			arg3 = args[3].(*dto.UpdateAddressReq)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AddressService_Update_Call) Return(address *model.Address, err error) *AddressService_Update_Call {
	_c.Call.Return(address, err)
	return _c
}

func (_c *AddressService_Update_Call) RunAndReturn(run func(ctx context.Context, id string, userID string, req *dto.UpdateAddressReq) (*model.Address, error)) *AddressService_Update_Call {
	_c.Call.Return(run)
	return _c
}
