// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"goshop/internal/user/dto"
	"goshop/internal/user/model"

	mock "github.com/stretchr/testify/mock"
)

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

type UserService_Expecter struct {
	mock *mock.Mock
}

func (_m *UserService) EXPECT() *UserService_Expecter {
	return &UserService_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function for the type UserService
func (_mock *UserService) ChangePassword(ctx context.Context, id string, req *dto.ChangePasswordReq) error {
	ret := _mock.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *dto.ChangePasswordReq) error); ok {
		r0 = returnFunc(ctx, id, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserService_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type UserService_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req *dto.ChangePasswordReq
func (_e *UserService_Expecter) ChangePassword(ctx interface{}, id interface{}, req interface{}) *UserService_ChangePassword_Call {
	return &UserService_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, id, req)}
}

func (_c *UserService_ChangePassword_Call) Run(run func(ctx context.Context, id string, req *dto.ChangePasswordReq)) *UserService_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *dto.ChangePasswordReq
		if args[2] != nil {
			arg2 = args[2].(*dto.ChangePasswordReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserService_ChangePassword_Call) Return(err error) *UserService_ChangePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserService_ChangePassword_Call) RunAndReturn(run func(ctx context.Context, id string, req *dto.ChangePasswordReq) error) *UserService_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type UserService
func (_mock *UserService) GetUserByID(ctx context.Context, id string) (*model.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserService_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type UserService_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UserService_Expecter) GetUserByID(ctx interface{}, id interface{}) *UserService_GetUserByID_Call {
	return &UserService_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *UserService_GetUserByID_Call) Run(run func(ctx context.Context, id string)) *UserService_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserService_GetUserByID_Call) Return(user *model.User, err error) *UserService_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserService_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.User, error)) *UserService_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type UserService
func (_mock *UserService) Login(ctx context.Context, req *dto.LoginReq) (*model.User, string, string, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *model.User
	var r1 string
	var r2 string
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.LoginReq) (*model.User, string, string, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.LoginReq) *model.User); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.LoginReq) string); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *dto.LoginReq) string); ok {
		r2 = returnFunc(ctx, req)
	} else {
		r2 = ret.Get(2).(string)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, *dto.LoginReq) error); ok {
		r3 = returnFunc(ctx, req)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// UserService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type UserService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.LoginReq
func (_e *UserService_Expecter) Login(ctx interface{}, req interface{}) *UserService_Login_Call {
	return &UserService_Login_Call{Call: _e.mock.On("Login", ctx, req)}
}

func (_c *UserService_Login_Call) Run(run func(ctx context.Context, req *dto.LoginReq)) *UserService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.LoginReq
		if args[1] != nil {
			arg1 = args[1].(*dto.LoginReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserService_Login_Call) Return(user *model.User, s string, s1 string, err error) *UserService_Login_Call {
	_c.Call.Return(user, s, s1, err)
	return _c
}

func (_c *UserService_Login_Call) RunAndReturn(run func(ctx context.Context, req *dto.LoginReq) (*model.User, string, string, error)) *UserService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function for the type UserService
func (_mock *UserService) RefreshToken(ctx context.Context, userID string) (string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserService_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type UserService_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *UserService_Expecter) RefreshToken(ctx interface{}, userID interface{}) *UserService_RefreshToken_Call {
	return &UserService_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, userID)}
}

func (_c *UserService_RefreshToken_Call) Run(run func(ctx context.Context, userID string)) *UserService_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserService_RefreshToken_Call) Return(s string, err error) *UserService_RefreshToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *UserService_RefreshToken_Call) RunAndReturn(run func(ctx context.Context, userID string) (string, error)) *UserService_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type UserService
func (_mock *UserService) Register(ctx context.Context, req *dto.RegisterReq) (*model.User, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.RegisterReq) (*model.User, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.RegisterReq) *model.User); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.RegisterReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type UserService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.RegisterReq
func (_e *UserService_Expecter) Register(ctx interface{}, req interface{}) *UserService_Register_Call {
	return &UserService_Register_Call{Call: _e.mock.On("Register", ctx, req)}
}

func (_c *UserService_Register_Call) Run(run func(ctx context.Context, req *dto.RegisterReq)) *UserService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.RegisterReq
		if args[1] != nil {
			arg1 = args[1].(*dto.RegisterReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserService_Register_Call) Return(user *model.User, err error) *UserService_Register_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserService_Register_Call) RunAndReturn(run func(ctx context.Context, req *dto.RegisterReq) (*model.User, error)) *UserService_Register_Call {
	_c.Call.Return(run)
	return _c
}
