// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"goshop/internal/user/dto"
	"goshop/internal/user/model"

	mock "github.com/stretchr/testify/mock"
)

// NewWishlistService creates a new instance of WishlistService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWishlistService(t interface {
	mock.TestingT
	Cleanup(func())
}) *WishlistService {
	mock := &WishlistService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WishlistService is an autogenerated mock type for the WishlistService type
type WishlistService struct {
	mock.Mock
}

type WishlistService_Expecter struct {
	mock *mock.Mock
}

func (_m *WishlistService) EXPECT() *WishlistService_Expecter {
	return &WishlistService_Expecter{mock: &_m.Mock}
}

// AddProduct provides a mock function for the type WishlistService
func (_mock *WishlistService) AddProduct(ctx context.Context, userID string, req *dto.AddToWishlistReq) error {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for AddProduct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *dto.AddToWishlistReq) error); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WishlistService_AddProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddProduct'
type WishlistService_AddProduct_Call struct {
	*mock.Call
}

// AddProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req *dto.AddToWishlistReq
func (_e *WishlistService_Expecter) AddProduct(ctx interface{}, userID interface{}, req interface{}) *WishlistService_AddProduct_Call {
	return &WishlistService_AddProduct_Call{Call: _e.mock.On("AddProduct", ctx, userID, req)}
}

func (_c *WishlistService_AddProduct_Call) Run(run func(ctx context.Context, userID string, req *dto.AddToWishlistReq)) *WishlistService_AddProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *dto.AddToWishlistReq
		if args[2] != nil {
			arg2 = args[2].(*dto.AddToWishlistReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WishlistService_AddProduct_Call) Return(err error) *WishlistService_AddProduct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WishlistService_AddProduct_Call) RunAndReturn(run func(ctx context.Context, userID string, req *dto.AddToWishlistReq) error) *WishlistService_AddProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetWishlist provides a mock function for the type WishlistService
func (_mock *WishlistService) GetWishlist(ctx context.Context, userID string) ([]*model.Wishlist, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWishlist")
	}

	var r0 []*model.Wishlist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*model.Wishlist, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*model.Wishlist); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Wishlist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WishlistService_GetWishlist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWishlist'
type WishlistService_GetWishlist_Call struct {
	*mock.Call
}

// GetWishlist is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *WishlistService_Expecter) GetWishlist(ctx interface{}, userID interface{}) *WishlistService_GetWishlist_Call {
	return &WishlistService_GetWishlist_Call{Call: _e.mock.On("GetWishlist", ctx, userID)}
}

func (_c *WishlistService_GetWishlist_Call) Run(run func(ctx context.Context, userID string)) *WishlistService_GetWishlist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WishlistService_GetWishlist_Call) Return(wishlists []*model.Wishlist, err error) *WishlistService_GetWishlist_Call {
	_c.Call.Return(wishlists, err)
	return _c
}

func (_c *WishlistService_GetWishlist_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*model.Wishlist, error)) *WishlistService_GetWishlist_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveProduct provides a mock function for the type WishlistService
func (_mock *WishlistService) RemoveProduct(ctx context.Context, userID string, productID string) error {
	ret := _mock.Called(ctx, userID, productID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveProduct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, productID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WishlistService_RemoveProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveProduct'
type WishlistService_RemoveProduct_Call struct {
	*mock.Call
}

// RemoveProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - productID string
func (_e *WishlistService_Expecter) RemoveProduct(ctx interface{}, userID interface{}, productID interface{}) *WishlistService_RemoveProduct_Call {
	return &WishlistService_RemoveProduct_Call{Call: _e.mock.On("RemoveProduct", ctx, userID, productID)}
}

func (_c *WishlistService_RemoveProduct_Call) Run(run func(ctx context.Context, userID string, productID string)) *WishlistService_RemoveProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WishlistService_RemoveProduct_Call) Return(err error) *WishlistService_RemoveProduct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WishlistService_RemoveProduct_Call) RunAndReturn(run func(ctx context.Context, userID string, productID string) error) *WishlistService_RemoveProduct_Call {
	_c.Call.Return(run)
	return _c
}
