// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"goshop/internal/user/model"

	mock "github.com/stretchr/testify/mock"
)

// NewAddressRepository creates a new instance of AddressRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAddressRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AddressRepository {
	mock := &AddressRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AddressRepository is an autogenerated mock type for the AddressRepository type
type AddressRepository struct {
	mock.Mock
}

type AddressRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AddressRepository) EXPECT() *AddressRepository_Expecter {
	return &AddressRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type AddressRepository
func (_mock *AddressRepository) Create(ctx context.Context, address *model.Address) error {
	ret := _mock.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Address) error); ok {
		r0 = returnFunc(ctx, address)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AddressRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type AddressRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - address *model.Address
func (_e *AddressRepository_Expecter) Create(ctx interface{}, address interface{}) *AddressRepository_Create_Call {
	return &AddressRepository_Create_Call{Call: _e.mock.On("Create", ctx, address)}
}

func (_c *AddressRepository_Create_Call) Run(run func(ctx context.Context, address *model.Address)) *AddressRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Address
		if args[1] != nil {
			arg1 = args[1].(*model.Address)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AddressRepository_Create_Call) Return(err error) *AddressRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AddressRepository_Create_Call) RunAndReturn(run func(ctx context.Context, address *model.Address) error) *AddressRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type AddressRepository
func (_mock *AddressRepository) Delete(ctx context.Context, id string, userID string) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AddressRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type AddressRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *AddressRepository_Expecter) Delete(ctx interface{}, id interface{}, userID interface{}) *AddressRepository_Delete_Call {
	return &AddressRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id, userID)}
}

func (_c *AddressRepository_Delete_Call) Run(run func(ctx context.Context, id string, userID string)) *AddressRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AddressRepository_Delete_Call) Return(err error) *AddressRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AddressRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string, userID string) error) *AddressRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type AddressRepository
func (_mock *AddressRepository) GetByID(ctx context.Context, id string, userID string) (*model.Address, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Address
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.Address, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.Address); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Address)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AddressRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type AddressRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *AddressRepository_Expecter) GetByID(ctx interface{}, id interface{}, userID interface{}) *AddressRepository_GetByID_Call {
	return &AddressRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id, userID)}
}

func (_c *AddressRepository_GetByID_Call) Run(run func(ctx context.Context, id string, userID string)) *AddressRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AddressRepository_GetByID_Call) Return(address *model.Address, err error) *AddressRepository_GetByID_Call {
	_c.Call.Return(address, err)
	return _c
}

func (_c *AddressRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string, userID string) (*model.Address, error)) *AddressRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type AddressRepository
func (_mock *AddressRepository) ListByUser(ctx context.Context, userID string) ([]*model.Address, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []*model.Address
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*model.Address, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*model.Address); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Address)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AddressRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type AddressRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *AddressRepository_Expecter) ListByUser(ctx interface{}, userID interface{}) *AddressRepository_ListByUser_Call {
	return &AddressRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *AddressRepository_ListByUser_Call) Run(run func(ctx context.Context, userID string)) *AddressRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AddressRepository_ListByUser_Call) Return(addresss []*model.Address, err error) *AddressRepository_ListByUser_Call {
	_c.Call.Return(addresss, err)
	return _c
}

func (_c *AddressRepository_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*model.Address, error)) *AddressRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// SetDefault provides a mock function for the type AddressRepository
func (_mock *AddressRepository) SetDefault(ctx context.Context, id string, userID string) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for SetDefault")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AddressRepository_SetDefault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDefault'
type AddressRepository_SetDefault_Call struct {
	*mock.Call
}

// SetDefault is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *AddressRepository_Expecter) SetDefault(ctx interface{}, id interface{}, userID interface{}) *AddressRepository_SetDefault_Call {
	return &AddressRepository_SetDefault_Call{Call: _e.mock.On("SetDefault", ctx, id, userID)}
}

func (_c *AddressRepository_SetDefault_Call) Run(run func(ctx context.Context, id string, userID string)) *AddressRepository_SetDefault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AddressRepository_SetDefault_Call) Return(err error) *AddressRepository_SetDefault_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AddressRepository_SetDefault_Call) RunAndReturn(run func(ctx context.Context, id string, userID string) error) *AddressRepository_SetDefault_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type AddressRepository
func (_mock *AddressRepository) Update(ctx context.Context, address *model.Address) error {
	ret := _mock.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Address) error); ok {
		r0 = returnFunc(ctx, address)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AddressRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type AddressRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - address *model.Address
func (_e *AddressRepository_Expecter) Update(ctx interface{}, address interface{}) *AddressRepository_Update_Call {
	return &AddressRepository_Update_Call{Call: _e.mock.On("Update", ctx, address)}
}

func (_c *AddressRepository_Update_Call) Run(run func(ctx context.Context, address *model.Address)) *AddressRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Address
		if args[1] != nil {
			arg1 = args[1].(*model.Address)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AddressRepository_Update_Call) Return(err error) *AddressRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AddressRepository_Update_Call) RunAndReturn(run func(ctx context.Context, address *model.Address) error) *AddressRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
