// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"goshop/internal/user/model"

	mock "github.com/stretchr/testify/mock"
)

// NewWishlistRepository creates a new instance of WishlistRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWishlistRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WishlistRepository {
	mock := &WishlistRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WishlistRepository is an autogenerated mock type for the WishlistRepository type
type WishlistRepository struct {
	mock.Mock
}

type WishlistRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *WishlistRepository) EXPECT() *WishlistRepository_Expecter {
	return &WishlistRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type WishlistRepository
func (_mock *WishlistRepository) Add(ctx context.Context, userID string, productID string) error {
	ret := _mock.Called(ctx, userID, productID)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, productID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WishlistRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type WishlistRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - productID string
func (_e *WishlistRepository_Expecter) Add(ctx interface{}, userID interface{}, productID interface{}) *WishlistRepository_Add_Call {
	return &WishlistRepository_Add_Call{Call: _e.mock.On("Add", ctx, userID, productID)}
}

func (_c *WishlistRepository_Add_Call) Run(run func(ctx context.Context, userID string, productID string)) *WishlistRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WishlistRepository_Add_Call) Return(err error) *WishlistRepository_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WishlistRepository_Add_Call) RunAndReturn(run func(ctx context.Context, userID string, productID string) error) *WishlistRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// GetWishlist provides a mock function for the type WishlistRepository
func (_mock *WishlistRepository) GetWishlist(ctx context.Context, userID string) ([]*model.Wishlist, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWishlist")
	}

	var r0 []*model.Wishlist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*model.Wishlist, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*model.Wishlist); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Wishlist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WishlistRepository_GetWishlist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWishlist'
type WishlistRepository_GetWishlist_Call struct {
	*mock.Call
}

// GetWishlist is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *WishlistRepository_Expecter) GetWishlist(ctx interface{}, userID interface{}) *WishlistRepository_GetWishlist_Call {
	return &WishlistRepository_GetWishlist_Call{Call: _e.mock.On("GetWishlist", ctx, userID)}
}

func (_c *WishlistRepository_GetWishlist_Call) Run(run func(ctx context.Context, userID string)) *WishlistRepository_GetWishlist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WishlistRepository_GetWishlist_Call) Return(wishlists []*model.Wishlist, err error) *WishlistRepository_GetWishlist_Call {
	_c.Call.Return(wishlists, err)
	return _c
}

func (_c *WishlistRepository_GetWishlist_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*model.Wishlist, error)) *WishlistRepository_GetWishlist_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type WishlistRepository
func (_mock *WishlistRepository) Remove(ctx context.Context, userID string, productID string) error {
	ret := _mock.Called(ctx, userID, productID)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, productID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WishlistRepository_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type WishlistRepository_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - productID string
func (_e *WishlistRepository_Expecter) Remove(ctx interface{}, userID interface{}, productID interface{}) *WishlistRepository_Remove_Call {
	return &WishlistRepository_Remove_Call{Call: _e.mock.On("Remove", ctx, userID, productID)}
}

func (_c *WishlistRepository_Remove_Call) Run(run func(ctx context.Context, userID string, productID string)) *WishlistRepository_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WishlistRepository_Remove_Call) Return(err error) *WishlistRepository_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WishlistRepository_Remove_Call) RunAndReturn(run func(ctx context.Context, userID string, productID string) error) *WishlistRepository_Remove_Call {
	_c.Call.Return(run)
	return _c
}
